import test from"node:test";import assert from"node:assert/strict";import{appendJournal,type BooksStore}from"./lifeline-books-engine.ts";import{reverseJournal,correctingJournal,accountingLineage}from"./accounting-corrections.ts";import{businessEvent,applyEventOnce,eventIntegrity}from"./business-event-engine.ts";
const empty=():BooksStore=>({journals:[],docs:[],bills:[],refunds:[],nextQuote:1,nextInvoice:1,nextCredit:1,lockDate:""});
test("posted journal is corrected by additive reversal, never mutation",()=>{const original={id:"j1",date:"2026-10-04",memo:"Sale",source:"SALE:1",lines:[{account:"Bank",side:"debit" as const,amount:110},{account:"Sales Revenue",side:"credit" as const,amount:110}]};const posted=appendJournal(empty(),original).store;const r=reverseJournal(posted,"SALE:1",{id:"r1",date:"2026-10-05",reason:"Wrong customer",actor:"owner"});assert.equal(r.added,true);assert.equal(r.store.journals.length,2);assert.deepEqual(r.store.journals.find(x=>x.source==="SALE:1"),original);assert.equal(accountingLineage(r.store,"SALE:1").corrected,true)});
test("correction is atomic to caller when replacement is invalid",()=>{const original={id:"j1",date:"2026-10-04",memo:"Sale",source:"SALE:1",lines:[{account:"Bank",side:"debit" as const,amount:100},{account:"Sales Revenue",side:"credit" as const,amount:100}]};const s=appendJournal(empty(),original).store;const bad={...original,id:"j2",source:"SALE:2",lines:[{account:"Bank",side:"debit" as const,amount:90},{account:"Sales Revenue",side:"credit" as const,amount:100}]};const r=correctingJournal(s,"SALE:1",bad,{reversalId:"r1",date:"2026-10-05",reason:"Correct amount",actor:"owner"});assert.equal(r.added,false);assert.equal(r.store,s)});
test("business events are idempotent by canonical event key",()=>{const e=businessEvent({type:"SALE_COMPLETED",businessId:"b",actorId:"u",occurredAt:"2026-10-04T00:00:00Z",entityType:"sale",entityId:"s1",correlationId:"checkout-1",payload:{total:99}});const seen=new Set<string>();let calls=0;assert.equal(applyEventOnce(seen,e,()=>{calls++}).applied,true);assert.equal(applyEventOnce(seen,e,()=>{calls++}).applied,false);assert.equal(calls,1);assert.equal(eventIntegrity([e]).valid,true)});

import{postOpeningBalance,postAccrual,postPrepayment,recognisePrepayment,writeOffReceivable}from"./accounting-adjustments.ts";import{issueInvoiceTransaction,receivePaymentTransaction,transactionIntegrity}from"./unified-transaction-engine.ts";
test("accounting adjustments remain balanced and duplicate safe",()=>{let s=empty();for(const r of [postOpeningBalance(s,{id:"o",date:"2026-10-01",source:"OPEN:1",memo:"Opening",account:"Bank",amount:1000,side:"debit"})]){assert.equal(r.added,true);s=r.store}let r=postAccrual(s,{id:"a",date:"2026-10-02",source:"ACCRUAL:1",memo:"Accrual",expenseAccount:"Operating Expense",liabilityAccount:"Accounts Payable",amount:100});assert.equal(r.added,true);s=r.store;r=postPrepayment(s,{id:"p",date:"2026-10-03",source:"PREPAY:1",memo:"Insurance",expenseAccount:"Insurance",amount:120});assert.equal(r.added,true);s=r.store;r=recognisePrepayment(s,{id:"pr",date:"2026-10-04",source:"PREPAY:RECOG:1",memo:"Insurance month",expenseAccount:"Insurance",amount:10});assert.equal(r.added,true);s=r.store;const w=writeOffReceivable(s,{id:"w",date:"2026-10-05",source:"BADDEBT:1",memo:"Write off",amount:110,gstComponent:10});assert.equal(w.added,true);assert.equal(w.store.journals.every(j=>{const d=j.lines.filter(x=>x.side==="debit").reduce((a,x)=>a+x.amount,0),cr=j.lines.filter(x=>x.side==="credit").reduce((a,x)=>a+x.amount,0);return Math.abs(d-cr)<.005}),true)});
test("unified invoice and payment transactions emit events only after ledger success",()=>{const doc={id:"i",number:"INV-1",kind:"invoice" as const,customer:"Customer",date:"2026-10-04",due:"",status:"sent" as const,items:[{description:"MRI",qty:1,rate:99,gst:"gst" as const}],payments:0,notes:""};const ctx={businessId:"b",actorId:"u",correlationId:"flow-1",at:"2026-10-04T01:00:00Z"};const issued=issueInvoiceTransaction(empty(),doc,ctx);assert.equal(issued.applied,true);assert.equal(transactionIntegrity(issued).valid,true);const duplicate=issueInvoiceTransaction(issued.store,doc,ctx);assert.equal(duplicate.applied,false);assert.equal(duplicate.events.length,0);const paid=receivePaymentTransaction(issued.store,doc,99,"pay1",{...ctx,correlationId:"flow-2"});assert.equal(paid.applied,true);assert.equal(paid.events[0].type,"PAYMENT_RECEIVED")});

import{recoveryAutomations,recoveryPriorityScore}from"./recovery-crm-automation.ts";import{evaluateWorkflow,workflowIntegrity,type WorkflowRule}from"./workflow-automation-engine.ts";
test("MRI deterioration creates deterministic CRM recovery work",()=>{const s={businessId:"b",accountId:"a",score:32,previousScore:44,cashRunwayDays:12,overdueRecoveryActions:2,nextRescanAt:"2026-10-01T00:00:00Z"};const a=recoveryAutomations(s,"2026-10-04T00:00:00Z");assert.deepEqual(new Set(a.map(x=>x.kind)),new Set(["health-drop","cash-critical","actions-overdue","rescan-due"]));assert.ok(recoveryPriorityScore(s)>=80)});
test("workflow engine applies conditions without arbitrary code execution",()=>{const rule:WorkflowRule={id:"r",name:"Critical health",enabled:true,trigger:"health-threshold",conditions:[{field:"score",operator:"lt",value:40},{field:"status",operator:"neq",value:"closed"}],actions:[{kind:"create-task",value:"Call owner"}]};assert.equal(workflowIntegrity([rule]).valid,true);assert.equal(evaluateWorkflow(rule,{trigger:"health-threshold",record:{score:30,status:"active"}}).length,1);assert.equal(evaluateWorkflow(rule,{trigger:"health-threshold",record:{score:60,status:"active"}}).length,0)});

import{fulfilSalesOrder}from"./erp-transaction-engine.ts";import type{OperatingStore}from"./lifeline-operations.ts";
test("ERP fulfilment is atomic across stock, invoice ledger and events",()=>{const now="2026-10-04T02:00:00Z";const ops:OperatingStore={industryPack:"retail",locations:[{id:"main",name:"Main",type:"store",active:true}],inventory:[{productId:"p",locationId:"main",onHand:5,allocated:0,available:5,averageCost:10}],movements:[],salesOrders:[{id:"so1",accountId:"a",status:"confirmed",lines:[{id:"l",description:"Item",quantity:2,unitPrice:55,taxRate:0,productId:"p"}],locationId:"main",createdAt:now,updatedAt:now}],purchaseOrders:[],projects:[],projectTasks:[],variations:[],progressClaims:[],serviceAgreements:[],serviceOrders:[],boms:[],routings:[],workCentres:[],productionOrders:[]};const r=fulfilSalesOrder({operations:ops,books:empty(),orderId:"so1",customerName:"Customer",actorId:"u",businessId:"b",at:now,correlationId:"fulfil-1"});assert.equal(r.applied,true);assert.equal(r.operations.inventory[0].onHand,3);assert.equal(r.books.journals.length,1);assert.equal(r.events.length,2);const bad=fulfilSalesOrder({operations:{...ops,inventory:[{...ops.inventory[0],available:1,onHand:1}]},books:empty(),orderId:"so1",customerName:"Customer",actorId:"u",businessId:"b",at:now,correlationId:"fulfil-2"});assert.equal(bad.applied,false);assert.equal(bad.books.journals.length,0);assert.equal(bad.events.length,0)});

import{explainClaim,contradictoryEvidence,operationalSignals}from"./mri-explainability.ts";import{createSnapshot,verifySnapshot,migrateSnapshot,optimisticWrite}from"./data-reliability.ts";
test("MRI claims expose evidence confidence contradictions and limitations",()=>{const evidence=[{id:"a",label:"monthly revenue",value:10000,source:"books" as const,confidence:95},{id:"b",label:"monthly revenue",value:12000,source:"user" as const,confidence:60}];const claim=explainClaim({id:"c",title:"Revenue pressure",severity:"high",explanation:"Revenue evidence requires review.",evidenceIds:["a","b","missing"]},evidence);assert.equal(claim.confidence,78);assert.ok(claim.limitations.length>=2);assert.equal(contradictoryEvidence(evidence).length,1);assert.ok(operationalSignals({cashRunwayDays:10,grossMarginPercent:8,stockoutCount:2}).length>=3)});
test("backups detect corruption migrate sequentially and reject stale writes",()=>{const s=createSnapshot({name:"Business",count:1},1,"2026-10-04T00:00:00Z");assert.equal(verifySnapshot(s).valid,true);assert.equal(verifySnapshot({...s,payload:{...s.payload,count:2}}).valid,false);const m=migrateSnapshot(s,2,[{from:1,to:2,run:p=>({...p,count:p.count+1})}],"2026-10-04T01:00:00Z");assert.equal(m.schemaVersion,2);assert.equal(m.payload.count,2);assert.equal(optimisticWrite({version:3,value:{x:1}},2,{x:2}).applied,false);assert.equal(optimisticWrite({version:3,value:{x:1}},3,{x:2}).applied,true)});

import{lifecycleAudit,failForRetry}from"./lifecycle-reliability.ts";
test("lifecycle audit rejects cross-module corruption",()=>{const good=lifecycleAudit({events:[],books:empty(),inventory:[{onHand:5,allocated:1,available:4}],mri:{score:62,confidence:80}});assert.equal(good.ready,true);const bad=lifecycleAudit({events:[],books:empty(),inventory:[{onHand:1,allocated:2,available:-1}],mri:{score:101}});assert.equal(bad.ready,false);assert.ok(bad.checks.filter(x=>!x.ok).length>=2)});
test("failed work retries with bounded exponential delay then dead-letters",()=>{let e={id:"job",attempt:0,maxAttempts:3,nextAttemptAt:"",payload:{event:"sale"}};const a=failForRetry(e,"network","2026-10-04T00:00:00Z");assert.equal(a.deadLetter,false);assert.equal(a.attempt,1);const b=failForRetry(a,"network","2026-10-04T00:00:10Z");assert.equal(b.deadLetter,false);const d=failForRetry(b,"network","2026-10-04T00:00:30Z");assert.equal(d.deadLetter,true);assert.equal(d.nextAttemptAt,"")});

import{evidenceFromEvents,eventFeedbackMetrics,correlationLineage}from"./operational-mri-feedback.ts";
test("operational events become traceable MRI evidence",()=>{const sale=businessEvent({type:"SALE_COMPLETED",businessId:"b",actorId:"u",occurredAt:"2026-10-04T00:00:00Z",entityType:"sale",entityId:"s",correlationId:"flow",payload:{total:250}});const pay=businessEvent({type:"PAYMENT_RECEIVED",businessId:"b",actorId:"u",occurredAt:"2026-10-04T00:01:00Z",entityType:"payment",entityId:"p",correlationId:"flow",causationId:sale.id,payload:{amount:100}});const evidence=evidenceFromEvents([sale,pay]);assert.equal(evidence.length,2);assert.deepEqual(eventFeedbackMetrics([sale,pay]),{paymentReceipts:100,sales:250,fulfilledValue:0,payrollGross:0,evidenceCount:2});const lineage=correlationLineage([sale,pay],"flow");assert.equal(lineage.valid,true);assert.equal(lineage.roots.length,1)});

import{auditEvent}from"./shared-platform.ts";import{linkAuditToEvent,auditLineageIntegrity}from"./audit-lineage.ts";
test("audit lineage links mutations to canonical events",()=>{const e=businessEvent({type:"SALE_COMPLETED",businessId:"b",actorId:"owner",occurredAt:"2026-10-04T02:00:00Z",entityType:"sale",entityId:"sale1",correlationId:"flow1",payload:{total:99}});const a=auditEvent({actor:"owner",action:"create",recordType:"sale",recordId:"sale1",summary:"Completed sale"},"2026-10-04T02:00:00Z");const link=linkAuditToEvent(a,e);assert.equal(link.eventId,e.id);assert.equal(auditLineageIntegrity([link],[e]).valid,true);assert.equal(auditLineageIntegrity([{...link,eventId:"missing"}],[e]).valid,false);assert.throws(()=>linkAuditToEvent({...a,actor:"other"},e))});

import{createWorkspaceBackup,roundTripBackup,verifyWorkspaceRestore}from"./workspace-backup-integrity.ts";
test("workspace backups round-trip and reject corrupted restores",()=>{const e=businessEvent({type:"SALE_COMPLETED",businessId:"b",actorId:"u",occurredAt:"2026-10-04T03:00:00Z",entityType:"sale",entityId:"s",correlationId:"c",payload:{total:50}});const s=createWorkspaceBackup({books:empty(),events:[e],metadata:{businessId:"b",exportedBy:"u"}},1,"2026-10-04T03:01:00Z");const rt=roundTripBackup(s);assert.equal(rt.verification.valid,true);const corrupt={...s,payload:{...s.payload,metadata:{...s.payload.metadata,businessId:""}}};assert.equal(verifyWorkspaceRestore(corrupt).valid,false)});
