import test from"node:test";import assert from"node:assert/strict";import{appendJournal,type BooksStore}from"./lifeline-books-engine.ts";import{reverseJournal,correctingJournal,accountingLineage}from"./accounting-corrections.ts";import{businessEvent,applyEventOnce,eventIntegrity}from"./business-event-engine.ts";
const empty=():BooksStore=>({journals:[],docs:[],bills:[],refunds:[],nextQuote:1,nextInvoice:1,nextCredit:1,lockDate:""});
test("posted journal is corrected by additive reversal, never mutation",()=>{const original={id:"j1",date:"2026-10-04",memo:"Sale",source:"SALE:1",lines:[{account:"Bank",side:"debit" as const,amount:110},{account:"Sales Revenue",side:"credit" as const,amount:110}]};const posted=appendJournal(empty(),original).store;const r=reverseJournal(posted,"SALE:1",{id:"r1",date:"2026-10-05",reason:"Wrong customer",actor:"owner"});assert.equal(r.added,true);assert.equal(r.store.journals.length,2);assert.deepEqual(r.store.journals.find(x=>x.source==="SALE:1"),original);assert.equal(accountingLineage(r.store,"SALE:1").corrected,true)});
test("correction is atomic to caller when replacement is invalid",()=>{const original={id:"j1",date:"2026-10-04",memo:"Sale",source:"SALE:1",lines:[{account:"Bank",side:"debit" as const,amount:100},{account:"Sales Revenue",side:"credit" as const,amount:100}]};const s=appendJournal(empty(),original).store;const bad={...original,id:"j2",source:"SALE:2",lines:[{account:"Bank",side:"debit" as const,amount:90},{account:"Sales Revenue",side:"credit" as const,amount:100}]};const r=correctingJournal(s,"SALE:1",bad,{reversalId:"r1",date:"2026-10-05",reason:"Correct amount",actor:"owner"});assert.equal(r.added,false);assert.equal(r.store,s)});
test("business events are idempotent by canonical event key",()=>{const e=businessEvent({type:"SALE_COMPLETED",businessId:"b",actorId:"u",occurredAt:"2026-10-04T00:00:00Z",entityType:"sale",entityId:"s1",correlationId:"checkout-1",payload:{total:99}});const seen=new Set<string>();let calls=0;assert.equal(applyEventOnce(seen,e,()=>{calls++}).applied,true);assert.equal(applyEventOnce(seen,e,()=>{calls++}).applied,false);assert.equal(calls,1);assert.equal(eventIntegrity([e]).valid,true)});

import{postOpeningBalance,postAccrual,postPrepayment,recognisePrepayment,writeOffReceivable}from"./accounting-adjustments.ts";import{issueInvoiceTransaction,receivePaymentTransaction,transactionIntegrity}from"./unified-transaction-engine.ts";
test("accounting adjustments remain balanced and duplicate safe",()=>{let s=empty();for(const r of [postOpeningBalance(s,{id:"o",date:"2026-10-01",source:"OPEN:1",memo:"Opening",account:"Bank",amount:1000,side:"debit"})]){assert.equal(r.added,true);s=r.store}let r=postAccrual(s,{id:"a",date:"2026-10-02",source:"ACCRUAL:1",memo:"Accrual",expenseAccount:"Operating Expense",liabilityAccount:"Accounts Payable",amount:100});assert.equal(r.added,true);s=r.store;r=postPrepayment(s,{id:"p",date:"2026-10-03",source:"PREPAY:1",memo:"Insurance",expenseAccount:"Insurance",amount:120});assert.equal(r.added,true);s=r.store;r=recognisePrepayment(s,{id:"pr",date:"2026-10-04",source:"PREPAY:RECOG:1",memo:"Insurance month",expenseAccount:"Insurance",amount:10});assert.equal(r.added,true);s=r.store;const w=writeOffReceivable(s,{id:"w",date:"2026-10-05",source:"BADDEBT:1",memo:"Write off",amount:110,gstComponent:10});assert.equal(w.added,true);assert.equal(w.store.journals.every(j=>{const d=j.lines.filter(x=>x.side==="debit").reduce((a,x)=>a+x.amount,0),cr=j.lines.filter(x=>x.side==="credit").reduce((a,x)=>a+x.amount,0);return Math.abs(d-cr)<.005}),true)});
test("unified invoice and payment transactions emit events only after ledger success",()=>{const doc={id:"i",number:"INV-1",kind:"invoice" as const,customer:"Customer",date:"2026-10-04",due:"",status:"sent" as const,items:[{description:"MRI",qty:1,rate:99,gst:"gst" as const}],payments:0,notes:""};const ctx={businessId:"b",actorId:"u",correlationId:"flow-1",at:"2026-10-04T01:00:00Z"};const issued=issueInvoiceTransaction(empty(),doc,ctx);assert.equal(issued.applied,true);assert.equal(transactionIntegrity(issued).valid,true);const duplicate=issueInvoiceTransaction(issued.store,doc,ctx);assert.equal(duplicate.applied,false);assert.equal(duplicate.events.length,0);const paid=receivePaymentTransaction(issued.store,doc,99,"pay1",{...ctx,correlationId:"flow-2"});assert.equal(paid.applied,true);assert.equal(paid.events[0].type,"PAYMENT_RECEIVED")});
