import{appendJournal,type BooksStore,type LedgerJournal}from"./lifeline-books-engine.ts";
const round=(n:number)=>Math.round((Number(n)||0)*100)/100;
type PostInput={id:string;date:string;source:string;memo:string};
const post=(s:BooksStore,i:PostInput,lines:LedgerJournal["lines"])=>appendJournal(s,{id:i.id,date:i.date,source:i.source,memo:i.memo,lines});
export function postOpeningBalance(s:BooksStore,i:PostInput&{account:string;amount:number;side:"debit"|"credit";equityAccount?:string}){const v=round(Math.abs(i.amount));if(!v)return{store:s,added:false,reason:"invalid-amount" as const};const opposite=i.side==="debit"?"credit":"debit";return post(s,i,[{account:i.account,side:i.side,amount:v},{account:i.equityAccount??"Owner Equity",side:opposite,amount:v}])}
export function postAccrual(s:BooksStore,i:PostInput&{expenseAccount:string;liabilityAccount:string;amount:number}){const v=round(Math.abs(i.amount));return v?post(s,i,[{account:i.expenseAccount,side:"debit",amount:v},{account:i.liabilityAccount,side:"credit",amount:v}]):{store:s,added:false,reason:"invalid-amount" as const}}
export function postPrepayment(s:BooksStore,i:PostInput&{expenseAccount:string;amount:number}){const v=round(Math.abs(i.amount));return v?post(s,i,[{account:"Prepayments",side:"debit",amount:v},{account:"Bank",side:"credit",amount:v}]):{store:s,added:false,reason:"invalid-amount" as const}}
export function recognisePrepayment(s:BooksStore,i:PostInput&{expenseAccount:string;amount:number}){const v=round(Math.abs(i.amount));return v?post(s,i,[{account:i.expenseAccount,side:"debit",amount:v},{account:"Prepayments",side:"credit",amount:v}]):{store:s,added:false,reason:"invalid-amount" as const}}
export function writeOffReceivable(s:BooksStore,i:PostInput&{amount:number;gstComponent?:number}){const v=round(Math.abs(i.amount)),gst=round(Math.max(0,i.gstComponent??0));if(!v||gst>v)return{store:s,added:false,reason:"invalid-amount" as const};const lines:LedgerJournal["lines"]=[{account:"Bad Debts",side:"debit",amount:round(v-gst)}];if(gst)lines.push({account:"GST Payable",side:"debit",amount:gst});lines.push({account:"Accounts Receivable",side:"credit",amount:v});return post(s,i,lines)}
