import type { BusinessData, HealthMetrics } from "./types.ts";
import type { SmartImportDraft } from "./mri-smart-import.ts";
import type { MriAccuracyProfile } from "./mri-accuracy-profile.ts";
import { assessMriAccuracyProfile } from "./mri-accuracy-profile.ts";
export type EvidenceGrade="A"|"B"|"C"|"D"; export type HealthDomain={key:string;label:string;score:number;weight:number;status:"strong"|"watch"|"high"|"critical";evidence:string};
export type DiagnosticStandard={version:"BLH-1.2";score:number;rawScore:number;pressure:HealthMetrics["pressureLevel"];evidenceGrade:EvidenceGrade;evidenceConfidence:number;domains:HealthDomain[];redFlags:string[];professionalReview:boolean;dataWarnings:string[];limitations:string[]};
export type EvidenceContext={draft?:SmartImportDraft|null;accuracyProfile?:MriAccuracyProfile|null};
const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n))); const status=(n:number):HealthDomain["status"]=>n>=75?"strong":n>=55?"watch":n>=35?"high":"critical";
export function evidenceGrade(data:BusinessData,m:HealthMetrics,verified=false){let c=m.dataConfidence;if(verified)c=Math.min(100,c+15);if(data.accountsReceivable>=data.overdueInvoices)c+=3;if(data.monthlyRevenue>0&&data.fixedExpenses+data.variableExpenses>0)c+=2;c=clamp(c);return{confidence:c,grade:(c>=90?"A":c>=75?"B":c>=55?"C":"D") as EvidenceGrade}}
export function diagnosticStandard(data:BusinessData,m:HealthMetrics,verified=false,context:EvidenceContext={}):DiagnosticStandard{const ev=evidenceGrade(data,m,verified);const dataWarnings:string[]=[];if(data.overdueInvoices>data.accountsReceivable)dataWarnings.push("Overdue invoices exceed total receivables.");if(data.monthlyRevenue<=0&&data.yearsOperating>0)dataWarnings.push("Trading business has no current monthly revenue.");if(data.fixedExpenses+data.variableExpenses<=0&&data.monthlyRevenue>0)dataWarnings.push("Revenue is present but no operating expenses were supplied.");const confirmed=context.draft?.fields.filter(f=>f.confidence==="high").length??0;const conflicts=context.draft?.conflicts?.length??0;const profile=context.accuracyProfile?assessMriAccuracyProfile(context.accuracyProfile):null;if(conflicts)dataWarnings.push(`${conflicts} imported field conflict${conflicts===1?"":"s"} require confirmation.`);const domainsBase: Omit<HealthDomain,"status">[]=[
{key:"cash",label:"Cash generation & runway",score:clamp(m.cashFlowScore*.55+m.runwayScore*.45),weight:24,evidence:"Operating cash result, cash balance and loss runway"},
{key:"liquidity",label:"Liquidity & obligations",score:clamp(m.liquidityScore*.55+m.obligationsScore*.45),weight:22,evidence:"Liquid resources versus overdue and near-term obligations"},
{key:"profit",label:"Profitability & cost structure",score:clamp(50+m.operatingMargin*2),weight:18,evidence:"Operating margin and expense burden"},
{key:"debt",label:"Debt resilience",score:m.debtScore,weight:14,evidence:"Recorded debt relative to annualised revenue and arrears"},
{key:"revenue",label:"Revenue resilience",score:m.revenueScore,weight:10,evidence:"Reported revenue trend and stability"},
{key:"working-capital",label:"Working capital",score:clamp(100-Math.min(100,m.receivablesPressure*1.5)-(data.overdueSuppliers>0?20:0)),weight:12,evidence:"Overdue receivables and supplier pressure"}];const domains:HealthDomain[]=domainsBase.map(d=>({...d,status:status(d.score)}));
const redFlags=[...m.criticalTriggers,...(profile?.risks??[])];if(data.overdueTax>0)redFlags.push("Overdue tax reported");if(data.overdueSuppliers>0)redFlags.push("Overdue suppliers reported");if(m.monthlyOperatingResult<0)redFlags.push("Current monthly cash result is negative");const concern=data.urgentConcerns.join(" ").toLowerCase();const professionalReview=redFlags.length>0||/(statutory demand|court|director penalty|insolven|wage|super|legal)/.test(concern);const rawScore=Math.round(domains.reduce((n,d)=>n+d.score*d.weight,0)/100);let score=Math.min(rawScore,m.overallScore+8);if(m.criticalTriggers.length>=2)score=Math.min(score,24);else if(m.criticalTriggers.length===1)score=Math.min(score,39);if(dataWarnings.length>=2)score=Math.min(score,69);const evidenceBoost=Math.min(10,confirmed*2)+(profile?Math.round(profile.confidence*.08):0);const evidencePenalty=dataWarnings.length*10+conflicts*5;const evidenceConfidence=clamp(ev.confidence+evidenceBoost-evidencePenalty);const evidenceGradeFinal=(evidenceConfidence>=90?"A":evidenceConfidence>=75?"B":evidenceConfidence>=55?"C":"D") as EvidenceGrade;return{version:"BLH-1.2",score,rawScore,pressure:m.pressureLevel,evidenceGrade:evidenceGradeFinal,evidenceConfidence,domains,redFlags:[...new Set(redFlags)],professionalReview,dataWarnings,limitations:["Screening and decision-support standard, not an insolvency determination, audit, valuation, tax opinion or legal conclusion.","Accuracy depends on completeness, currency and reconciliation of supplied records.","Industry comparison should use a current applicable benchmark and turnover band where available."]}}
