import test from"node:test";import assert from"node:assert/strict";import{calculateHealth}from"./calculations.ts";import{diagnosticStandard}from"./business-health-standard.ts";import{demoBusiness}from"./demo.ts";
test("BLH standard exposes weighted domains and evidence quality",()=>{const s=diagnosticStandard(demoBusiness,calculateHealth(demoBusiness));assert.equal(s.version,"BLH-1.2");assert.equal(s.domains.reduce((n,d)=>n+d.weight,0),100);assert.ok(s.evidenceConfidence>=0&&s.evidenceConfidence<=100);assert.ok(["A","B","C","D"].includes(s.evidenceGrade))});
test("distress flags force professional review",()=>{const d={...demoBusiness,overdueTax:50000,cashAvailable:1000};const s=diagnosticStandard(d,calculateHealth(d));assert.equal(s.professionalReview,true);assert.ok(s.redFlags.length>0)});
test("contradictory evidence lowers confidence",()=>{const d={...demoBusiness,accountsReceivable:100,overdueInvoices:5000};const s=diagnosticStandard(d,calculateHealth(d));assert.ok(s.dataWarnings.length>0);assert.ok(s.evidenceConfidence<100)});
test("domain weighted score cannot hide multiple critical triggers",()=>{const d={...demoBusiness,overdueTax:50000,overdueSuppliers:30000,cashAvailable:500,monthlyRevenue:10000,fixedExpenses:12000,variableExpenses:5000};const s=diagnosticStandard(d,calculateHealth(d));assert.ok(s.score<=24);assert.equal(s.professionalReview,true)});
test("healthy business remains outside distress bands",()=>{const d={...demoBusiness,monthlyRevenue:100000,fixedExpenses:30000,variableExpenses:30000,ownerDrawings:5000,loanRepayments:2000,cashAvailable:250000,accountsReceivable:20000,overdueInvoices:1000,totalDebt:20000,overdueTax:0,overdueSuppliers:0,revenueTrend:"growing" as const,urgentConcerns:[]};const s=diagnosticStandard(d,calculateHealth(d),true);assert.ok(s.score>=60);assert.equal(s.professionalReview,false)});
test("score and every domain stay bounded 0 to 100",()=>{for(const d of [demoBusiness,{...demoBusiness,monthlyRevenue:1,totalDebt:999999999,overdueTax:999999,cashAvailable:0}]){const s=diagnosticStandard(d,calculateHealth(d));assert.ok(s.score>=0&&s.score<=100);for(const domain of s.domains)assert.ok(domain.score>=0&&domain.score<=100)}});
test("confirmed import evidence increases confidence without changing health score",()=>{const base=diagnosticStandard(demoBusiness,calculateHealth(demoBusiness));const draft={fields:[{key:"monthlyRevenue" as const,value:demoBusiness.monthlyRevenue,source:"P&L",confidence:"high" as const}],conflicts:[],updatedAt:new Date(0).toISOString()};const withEvidence=diagnosticStandard(demoBusiness,calculateHealth(demoBusiness),false,{draft});assert.equal(withEvidence.score,base.score);assert.ok(withEvidence.evidenceConfidence>=base.evidenceConfidence)});
test("import conflicts reduce evidence confidence and surface a warning",()=>{const draft={fields:[],conflicts:[{key:"monthlyRevenue" as const,selected:{key:"monthlyRevenue" as const,value:100,source:"A",confidence:"high" as const},alternatives:[{key:"monthlyRevenue" as const,value:200,source:"B",confidence:"high" as const}],reason:"conflict"}],updatedAt:new Date(0).toISOString()};const s=diagnosticStandard(demoBusiness,calculateHealth(demoBusiness),false,{draft});assert.ok(s.dataWarnings.some(x=>x.includes("conflict")));assert.ok(s.evidenceConfidence<100)});
