import test from"node:test";import assert from"node:assert/strict";import{scanBarcode,createPutAway,createPick,completeWarehouseTask,returnToStock,manufacturingCost,workCentreLoad,mrpRequirements,traceLot,productionPlan}from"./lifeline-specialist.ts";
test("barcode scan resolves sku or barcode",()=>assert.equal(scanBarcode([{id:"1",sku:"ABC",barcode:"9301"}],"9301")?.id,"1"));
test("warehouse receiving put-away picking packing primitives",()=>{assert.equal(createPutAway({productId:"p",quantity:5},"A1").kind,"put-away");assert.equal(completeWarehouseTask(createPick("p",2,"A1")).status,"complete")});
test("returns restore stock",()=>assert.equal(returnToStock([{productId:"p",locationId:"w",onHand:2,allocated:0,available:2,averageCost:3}],"p","w",1)[0].onHand,3));
test("manufacturing costing includes materials labour overhead",()=>assert.deepEqual(manufacturingCost({materialCost:100,labourHours:2,labourRate:40,overheadRatePerHour:10,outputQuantity:10}),{materials:100,labour:80,overhead:20,total:200,unitCost:20}));
test("MRP nets available inventory",()=>{const r=mrpRequirements({id:"b",outputProductId:"x",outputQuantity:1,version:"1",active:true,components:[{productId:"c",quantity:2}]},5,[{productId:"c",locationId:"w",onHand:3,allocated:0,available:3,averageCost:1}]);assert.equal(r[0].netRequirement,7)});
test("capacity calculates work-centre utilisation",()=>{const c=workCentreLoad([{quantity:2,routing:{id:"r",outputProductId:"x",version:"1",operations:[{id:"o",sequence:1,workCentreId:"wc",description:"Cut",setupMinutes:10,runMinutes:25}]}}],[{id:"wc",name:"Saw",hourlyCapacity:2,costPerHour:50,active:true}]);assert.equal(c[0].requiredMinutes,60);assert.equal(c[0].utilisationPercent,50)});
test("lot trace is chronological",()=>assert.equal(traceLot([{id:"2",lot:"L",productId:"p",kind:"ship",sourceId:"s",at:"2026-02-02",quantity:1},{id:"1",lot:"L",productId:"p",kind:"receive",sourceId:"r",at:"2026-01-01",quantity:1}],"L")[0].kind,"receive"));
test("production planning orders by due date",()=>{const p=productionPlan([{id:"2",productId:"x",quantity:1,bomId:"b",status:"planned",dueAt:"2026-12-02",consumed:{},outputQuantity:0,createdAt:"x"},{id:"1",productId:"x",quantity:1,bomId:"b",status:"planned",dueAt:"2026-11-01",consumed:{},outputQuantity:0,createdAt:"x"}],[]);assert.equal(p[0].orderId,"1")});
