import type{BillOfMaterial,InventoryBalance,ProductionOrder,Routing,WorkCentre}from"./lifeline-operations";
export type Bin={id:string;locationId:string;code:string;active:boolean};
export type WarehouseTask={id:string;kind:"put-away"|"pick"|"pack"|"return";productId:string;quantity:number;fromBinId?:string;toBinId?:string;status:"open"|"in-progress"|"complete"};
export function scanBarcode<T extends{barcode?:string;sku?:string;id?:string}>(items:T[],code:string){const q=code.trim().toLowerCase();return items.find(x=>[x.barcode,x.sku,x.id].some(v=>String(v||"").toLowerCase()===q))||null}
export function createPutAway(receipt:{productId:string;quantity:number},toBinId:string):WarehouseTask{return{id:"put-"+receipt.productId+"-"+toBinId,kind:"put-away",productId:receipt.productId,quantity:Math.max(0,receipt.quantity),toBinId,status:"open"}}
export function createPick(productId:string,quantity:number,fromBinId:string):WarehouseTask{if(quantity<=0)throw new Error("Pick quantity must be positive.");return{id:"pick-"+productId+"-"+fromBinId,kind:"pick",productId,quantity,fromBinId,status:"open"}}
export function completeWarehouseTask(task:WarehouseTask){return{...task,status:"complete" as const}}
export function returnToStock(balance:InventoryBalance[],productId:string,locationId:string,quantity:number){if(quantity<=0)throw new Error("Return quantity must be positive.");const found=balance.find(x=>x.productId===productId&&x.locationId===locationId);if(!found)throw new Error("Stock item not found.");return balance.map(x=>x===found?{...x,onHand:x.onHand+quantity,available:x.available+quantity}:x)}
export function manufacturingCost(input:{materialCost:number;labourHours:number;labourRate:number;overheadRatePerHour:number;outputQuantity:number}){const materials=Math.max(0,input.materialCost),labour=Math.max(0,input.labourHours)*Math.max(0,input.labourRate),overhead=Math.max(0,input.labourHours)*Math.max(0,input.overheadRatePerHour),total=materials+labour+overhead;return{materials,labour,overhead,total,unitCost:input.outputQuantity>0?total/input.outputQuantity:0}}
export function workCentreLoad(orders:Array<{routing?:Routing;quantity:number}>,centres:WorkCentre[]){return centres.map(c=>{const minutes=orders.reduce((sum,o)=>sum+(o.routing?.operations.filter(op=>op.workCentreId===c.id).reduce((n,op)=>n+op.setupMinutes+op.runMinutes*Math.max(0,o.quantity),0)||0),0);const capacityMinutes=Math.max(0,c.hourlyCapacity)*60;return{workCentreId:c.id,requiredMinutes:minutes,capacityMinutes,utilisationPercent:capacityMinutes?minutes/capacityMinutes*100:0}})}
export function mrpRequirements(bom:BillOfMaterial,quantity:number,stock:InventoryBalance[]){const factor=quantity/Math.max(1,bom.outputQuantity);return bom.components.map(c=>{const gross=c.quantity*factor*(1+Math.max(0,c.scrapPercent||0)/100),available=stock.filter(x=>x.productId===c.productId).reduce((n,x)=>n+x.available,0);return{productId:c.productId,grossRequirement:gross,available,netRequirement:Math.max(0,gross-available)}})}
export type TraceEvent={id:string;lot:string;productId:string;kind:"receive"|"consume"|"produce"|"ship"|"return";sourceId:string;at:string;quantity:number};
export function traceLot(events:TraceEvent[],lot:string){return events.filter(x=>x.lot===lot).sort((a,b)=>a.at.localeCompare(b.at))}
export function productionPlan(orders:ProductionOrder[],stock:InventoryBalance[]){return orders.filter(o=>o.status!=="complete"&&o.status!=="cancelled").map(o=>({orderId:o.id,productId:o.productId,quantity:o.quantity,dueAt:o.dueAt,availableFinished:stock.filter(x=>x.productId===o.productId).reduce((n,x)=>n+x.available,0)})).sort((a,b)=>String(a.dueAt||"9999").localeCompare(String(b.dueAt||"9999")))}
