import type{ImportedField,SmartImportDraft}from"./mri-smart-import.ts";import type{BusinessData}from"./types.ts";
export type EvidenceSourceKind="bank"|"books"|"tax"|"payroll"|"crm"|"inventory"|"owner"|"statement"|"other";
export type ReconciliationCandidate=ImportedField&{sourceKind:EvidenceSourceKind;observedAt?:string};
export type ReconciledField={key:keyof BusinessData;status:"confirmed"|"provisional"|"conflict"|"stale";selected:ReconciliationCandidate;alternatives:ReconciliationCandidate[];confidence:number;reason:string};
const reliability:Record<EvidenceSourceKind,number>={bank:96,books:94,tax:94,payroll:92,inventory:90,statement:88,crm:82,owner:65,other:60};
const ageDays=(date:string|undefined,now:string)=>date?Math.max(0,(Date.parse(now)-Date.parse(date))/86400000):0;
const numericDiff=(a:number|string,b:number|string)=>typeof a==="number"&&typeof b==="number"?Math.abs(a-b)/Math.max(1,Math.abs(a),Math.abs(b)):String(a).trim().toLowerCase()===String(b).trim().toLowerCase()?0:1;
export function reconcileCandidates(candidates:ReconciliationCandidate[],now:string):ReconciledField[]{
 const by=new Map<keyof BusinessData,ReconciliationCandidate[]>();for(const c of candidates){const a=by.get(c.key)??[];a.push(c);by.set(c.key,a)}
 return[...by.entries()].map(([key,items])=>{const ranked=[...items].sort((a,b)=>{const as=reliability[a.sourceKind]-(ageDays(a.observedAt,now)>45?20:0),bs=reliability[b.sourceKind]-(ageDays(b.observedAt,now)>45?20:0);return bs-as});const selected=ranked[0],alternatives=ranked.slice(1);const stale=ageDays(selected.observedAt,now)>45;const conflict=alternatives.some(x=>numericDiff(selected.value,x.value)>.02);let confidence=reliability[selected.sourceKind];if(stale)confidence-=20;if(conflict)confidence-=Math.min(35,alternatives.filter(x=>numericDiff(selected.value,x.value)>.02).length*12);if(selected.confidence==="review")confidence-=15;confidence=Math.max(0,Math.min(100,Math.round(confidence)));const status=conflict?"conflict":stale?"stale":confidence>=85?"confirmed":"provisional";const reason=conflict?"Sources disagree materially; reconcile before relying on precise conclusions.":stale?"Best available source is stale; obtain a current record.":status==="confirmed"?"Independent/source-system evidence is sufficiently consistent.":"Evidence is usable provisionally but should be confirmed.";return{key,status,selected,alternatives,confidence,reason}})}
export function reconciliationSummary(fields:ReconciledField[]){const conflicts=fields.filter(x=>x.status==="conflict"),stale=fields.filter(x=>x.status==="stale"),confirmed=fields.filter(x=>x.status==="confirmed");const confidence=fields.length?Math.round(fields.reduce((n,x)=>n+x.confidence,0)/fields.length):0;return{confidence,confirmed:confirmed.length,conflicts:conflicts.length,stale:stale.length,requiresVerification:[...conflicts,...stale,...fields.filter(x=>x.status==="provisional")].map(x=>x.key),safeForPrecision:conflicts.length===0&&confidence>=80}}
export function reconciliationToDraft(fields:ReconciledField[],updatedAt:string):SmartImportDraft{return{fields:fields.map(x=>x.selected),conflicts:fields.filter(x=>x.status==="conflict").map(x=>({key:x.key,selected:x.selected,alternatives:x.alternatives,reason:x.reason})),warnings:fields.filter(x=>x.status==="stale").map(x=>`${String(x.key)} evidence is stale.`),updatedAt}}
