import test from"node:test";import assert from"node:assert/strict";
import{demoBusiness}from"./demo.ts";import{generateReport}from"./planner.ts";import{diagnosticStandard}from"./business-health-standard.ts";import{buildRecoveryFindings}from"./recovery-engine.ts";import{createEmptyCrmStore}from"./lifeline-crm.ts";import{advanceOpportunity,crmIntegrity}from"./customer-lifecycle.ts";import{postInvoice,type BooksStore,type SalesDocument}from"./lifeline-books-engine.ts";import{booksIntegrity}from"./money-integrity.ts";import{preparePayRun,finalisePayRun,payrollRunIntegrity}from"./payroll-run.ts";import{putAway,allocatePick,completePick,warehouseIntegrity,type WarehouseState}from"./warehouse-engine.ts";import{releaseProduction,consumeProduction,completeProduction,type ManufacturingState}from"./manufacturing-execution.ts";
const now="2026-10-02T00:00:00.000Z";
test("v1 release chain: MRI to recovery",()=>{const r=generateReport(demoBusiness),s=diagnosticStandard(demoBusiness,r.metrics);assert.ok(s.score>=0&&s.score<=100);assert.ok(Array.isArray(buildRecoveryFindings(demoBusiness,r,s)))});
test("v1 release chain: CRM won deal creates delivery work",()=>{const s=createEmptyCrmStore();s.accounts.push({id:"a",name:"Customer",type:"customer",tags:[],customFields:{},createdAt:now,updatedAt:now});s.opportunities.push({id:"o",accountId:"a",pipelineId:"sales-default",stageId:"lead",title:"Recovery engagement",value:99,createdAt:now,updatedAt:now});const n=advanceOpportunity(s,"o","won",now);assert.equal(crmIntegrity(n).valid,true);assert.ok(n.tasks.some(t=>t.opportunityId==="o"))});
test("v1 release chain: invoice has balanced canonical ledger posting",()=>{const empty:BooksStore={journals:[],docs:[],bills:[],refunds:[],nextQuote:1,nextInvoice:1,nextCredit:1,lockDate:""};const d:SalesDocument={id:"i",number:"INV-1",kind:"invoice",customer:"Customer",date:"2026-10-02",due:"",status:"sent",items:[{description:"MRI",qty:1,rate:99,gst:"gst"}],payments:0,notes:""};const posted=postInvoice(empty,d).store;assert.equal(booksIntegrity({...posted,docs:[d]}).valid,true)});
test("v1 release chain: payroll finalisation remains auditable",()=>{const r=preparePayRun({id:"e",name:"Worker",hourlyRate:30,superRatePercent:12,withholdingRatePercent:20},[{kind:"ordinary",description:"Ordinary",hours:8,rate:30}],{id:"pay",periodStart:"2026-09-01",periodEnd:"2026-09-07"});const f=finalisePayRun(r,"2026-09-08");assert.equal(payrollRunIntegrity([f]).valid,true);assert.ok(f.warnings.some(x=>x.includes("estimate")))});
test("v1 release chain: warehouse put-away pick preserves stock",()=>{let s:WarehouseState={bins:[{id:"b",locationId:"main",code:"A1",active:true}],balances:[],tasks:[{id:"in",kind:"put-away",productId:"p",quantity:5,toBinId:"b",status:"open"},{id:"out",kind:"pick",productId:"p",quantity:2,fromBinId:"b",status:"open"}]};s=putAway(s,"in");s=allocatePick(s,"out");s=completePick(s,"out");assert.equal(s.balances[0].onHand,3);assert.equal(warehouseIntegrity(s).valid,true)});
test("v1 release chain: manufacturing creates traceable finished stock",()=>{const base:ManufacturingState={orders:[{id:"o",productId:"finished",quantity:1,bomId:"bom",status:"planned",consumed:{},outputQuantity:0,createdAt:now}],inventory:[{productId:"part",locationId:"main",onHand:2,allocated:0,available:2,averageCost:5}],boms:[{id:"bom",outputProductId:"finished",outputQuantity:1,version:"1",active:true,components:[{productId:"part",quantity:1}]}],routings:[{id:"r",outputProductId:"finished",version:"1",operations:[{id:"op",sequence:1,workCentreId:"wc",description:"Build",setupMinutes:0,runMinutes:30}]}],workCentres:[{id:"wc",name:"Bench",hourlyCapacity:8,costPerHour:60,active:true}],traceEvents:[]};let s=releaseProduction(base,"o");s=consumeProduction(s,"o","LOT","2026-10-02");const d=completeProduction(s,"o","main","LOT","2026-10-02",.5);assert.equal(d.state.orders[0].status,"complete");assert.equal(d.state.inventory.find(x=>x.productId==="finished")?.onHand,1);assert.ok(d.state.traceEvents.length>=2)});
