import type{Bin,WarehouseTask}from"./lifeline-specialist.ts";
export type BinBalance={productId:string;binId:string;onHand:number;allocated:number};
export type WarehouseState={bins:Bin[];balances:BinBalance[];tasks:WarehouseTask[]};
const qty=(n:number)=>Math.max(0,Number(n)||0);
export function binAvailable(b:BinBalance){return Math.max(0,b.onHand-b.allocated)}
export function putAway(state:WarehouseState,taskId:string){const t=state.tasks.find(x=>x.id===taskId);if(!t||t.kind!=="put-away"||!t.toBinId||t.status==="complete")throw new Error("Invalid put-away task.");const existing=state.balances.find(x=>x.productId===t.productId&&x.binId===t.toBinId);const balances=existing?state.balances.map(x=>x===existing?{...x,onHand:x.onHand+qty(t.quantity)}:x):[...state.balances,{productId:t.productId,binId:t.toBinId,onHand:qty(t.quantity),allocated:0}];return{...state,balances,tasks:state.tasks.map(x=>x.id===taskId?{...x,status:"complete" as const}:x)}}
export function allocatePick(state:WarehouseState,taskId:string){const t=state.tasks.find(x=>x.id===taskId);if(!t||t.kind!=="pick"||!t.fromBinId||t.status==="complete")throw new Error("Invalid pick task.");const b=state.balances.find(x=>x.productId===t.productId&&x.binId===t.fromBinId);if(!b||binAvailable(b)<t.quantity)throw new Error("Insufficient bin stock.");return{...state,balances:state.balances.map(x=>x===b?{...x,allocated:x.allocated+t.quantity}:x),tasks:state.tasks.map(x=>x.id===taskId?{...x,status:"in-progress" as const}:x)}}
export function completePick(state:WarehouseState,taskId:string){const t=state.tasks.find(x=>x.id===taskId);if(!t||t.kind!=="pick"||!t.fromBinId||t.status!=="in-progress")throw new Error("Pick must be allocated first.");const b=state.balances.find(x=>x.productId===t.productId&&x.binId===t.fromBinId);if(!b||b.allocated<t.quantity||b.onHand<t.quantity)throw new Error("Invalid bin allocation.");return{...state,balances:state.balances.map(x=>x===b?{...x,onHand:x.onHand-t.quantity,allocated:x.allocated-t.quantity}:x),tasks:state.tasks.map(x=>x.id===taskId?{...x,status:"complete" as const}:x)}}
export function transferBin(state:WarehouseState,productId:string,fromBinId:string,toBinId:string,quantity:number){const n=qty(quantity);if(n<=0)throw new Error("Transfer quantity must be positive.");const from=state.balances.find(x=>x.productId===productId&&x.binId===fromBinId);if(!from||binAvailable(from)<n)throw new Error("Insufficient bin stock.");const to=state.balances.find(x=>x.productId===productId&&x.binId===toBinId);let balances=state.balances.map(x=>x===from?{...x,onHand:x.onHand-n}:x);balances=to?balances.map(x=>x===to?{...x,onHand:x.onHand+n}:x):[...balances,{productId,binId:toBinId,onHand:n,allocated:0}];return{...state,balances}}
export function warehouseIntegrity(state:WarehouseState){const errors:string[]=[];for(const b of state.balances){if(b.onHand<0||b.allocated<0||b.allocated>b.onHand)errors.push(`Invalid bin balance ${b.productId}/${b.binId}.`);if(!state.bins.some(x=>x.id===b.binId&&x.active))errors.push(`Balance references missing/inactive bin ${b.binId}.`)}return{valid:errors.length===0,errors}}
