"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Side="debit"|"credit";
type Line={account:string;side:Side;amount:number};
type Journal={id:string;date:string;memo:string;lines:Line[];source:string};
type Item={description:string;qty:number;rate:number;gst:"gst"|"free"|"input"};
type Doc={id:string;number:string;kind:"quote"|"invoice"|"credit";customer:string;date:string;due:string;status:"draft"|"sent"|"accepted"|"part-paid"|"paid"|"void";items:Item[];payments:number;notes:string};
type Bill={id:string;number:string;supplier:string;date:string;due:string;amount:number;gst:number;status:"draft"|"approved"|"part-paid"|"paid";paid:number};
type Refund={id:string;reference:string;customer:string;amount:number;date:string;method:string};
type Store={journals:Journal[];docs:Doc[];bills:Bill[];refunds:Refund[];nextQuote:number;nextInvoice:number;nextCredit:number;lockDate:string};

const KEY="business-lifeline-advanced-accounting-v1";
const empty:Store={journals:[],docs:[],bills:[],refunds:[],nextQuote:1,nextInvoice:1,nextCredit:1,lockDate:""};
const id=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const money=(n:number)=>n.toLocaleString("en-AU",{style:"currency",currency:"AUD"});
const pad=(n:number)=>String(n).padStart(5,"0");
const calc=(items:Item[])=>{const subtotal=items.reduce((s,i)=>s+i.qty*i.rate,0);const gst=items.reduce((s,i)=>s+(i.gst==="gst"?i.qty*i.rate/11:0),0);return{subtotal,gst,total:subtotal};};

export function AdvancedAccountingHub(){
 const [store,setStore]=useState<Store>(empty);const[ready,setReady]=useState(false);const[tab,setTab]=useState<"dashboard"|"journals"|"sales"|"bills"|"payments"|"reports">("dashboard");
 const[journal,setJournal]=useState({date:"",memo:"",debitAccount:"Bank",creditAccount:"Sales",amount:0});
 const[doc,setDoc]=useState({kind:"invoice" as Doc["kind"],customer:"",due:"",notes:"",items:[{description:"",qty:1,rate:0,gst:"gst" as Item["gst"]}]});
 const[bill,setBill]=useState({supplier:"",number:"",date:"",due:"",amount:0,gst:0});
 const[refund,setRefund]=useState({reference:"",customer:"",amount:0,date:"",method:"Bank transfer"});
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setStore({...empty,...JSON.parse(raw)})}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify(store))},[store,ready]);
 const trial=useMemo(()=>{const map=new Map<string,{debit:number;credit:number}>();store.journals.forEach(j=>j.lines.forEach(l=>{const v=map.get(l.account)||{debit:0,credit:0};v[l.side]+=l.amount;map.set(l.account,v)}));return [...map.entries()].map(([account,v])=>({account,...v,balance:v.debit-v.credit}))},[store.journals]);
 const ar=store.docs.filter(d=>d.kind==="invoice"&&d.status!=="paid"&&d.status!=="void").reduce((s,d)=>s+Math.max(0,calc(d.items).total-d.payments),0);
 const ap=store.bills.filter(b=>b.status!=="paid").reduce((s,b)=>s+Math.max(0,b.amount-b.paid),0);
 const sales=store.docs.filter(d=>d.kind==="invoice"&&d.status!=="void").reduce((s,d)=>s+calc(d.items).total,0);
 const gstCollected=store.docs.filter(d=>d.kind==="invoice"&&d.status!=="void").reduce((s,d)=>s+calc(d.items).gst,0);
 const gstCredits=store.bills.reduce((s,b)=>s+b.gst,0);
 const postJournal=(date:string,memo:string,lines:Line[],source:string)=>setStore(s=>({...s,journals:[{id:id("journal"),date:date||new Date().toISOString().slice(0,10),memo,lines,source},...s.journals]}));
 const addJournal=(e:FormEvent)=>{e.preventDefault();if(journal.amount<=0)return;postJournal(journal.date,journal.memo,[{account:journal.debitAccount,side:"debit",amount:journal.amount},{account:journal.creditAccount,side:"credit",amount:journal.amount}],"Manual");setJournal({date:"",memo:"",debitAccount:"Bank",creditAccount:"Sales",amount:0})};
 const createDoc=(e:FormEvent)=>{e.preventDefault();if(!doc.customer||!doc.items.some(i=>i.description&&i.rate>0))return;setStore(s=>{const key=doc.kind==="quote"?"nextQuote":doc.kind==="credit"?"nextCredit":"nextInvoice";const prefix=doc.kind==="quote"?"Q":doc.kind==="credit"?"CN":"INV";const number=`${prefix}-${pad(s[key])}`;return{...s,[key]:s[key]+1,docs:[{id:id("doc"),number,kind:doc.kind,customer:doc.customer,date:new Date().toISOString().slice(0,10),due:doc.due,status:"draft",items:doc.items,payments:0,notes:doc.notes},...s.docs]}});setDoc({kind:"invoice",customer:"",due:"",notes:"",items:[{description:"",qty:1,rate:0,gst:"gst"}]})};
 const recordDocPayment=(d:Doc)=>{const owing=Math.max(0,calc(d.items).total-d.payments);const amount=Number(prompt(`Amount received for ${d.number}`,String(owing))||0);if(amount<=0)return;setStore(s=>({...s,docs:s.docs.map(x=>x.id===d.id?{...x,payments:Math.min(calc(x.items).total,x.payments+amount),status:x.payments+amount>=calc(x.items).total?"paid":"part-paid"}:x)}));postJournal(new Date().toISOString().slice(0,10),`Payment ${d.number}`,[{account:"Bank",side:"debit",amount},{account:"Accounts Receivable",side:"credit",amount}],d.number)};
 const addBill=(e:FormEvent)=>{e.preventDefault();if(!bill.supplier||bill.amount<=0)return;const b:Bill={id:id("bill"),...bill,number:bill.number||`BILL-${pad(store.bills.length+1)}`,date:bill.date||new Date().toISOString().slice(0,10),status:"approved",paid:0};setStore(s=>({...s,bills:[b,...s.bills]}));postJournal(b.date,`Supplier bill ${b.number}`,[{account:"Expense",side:"debit",amount:b.amount-b.gst},{account:"GST Input Credit",side:"debit",amount:b.gst},{account:"Accounts Payable",side:"credit",amount:b.amount}],b.number);setBill({supplier:"",number:"",date:"",due:"",amount:0,gst:0})};
 const payBill=(b:Bill)=>{const owing=b.amount-b.paid;const amount=Number(prompt(`Payment for ${b.number}`,String(owing))||0);if(amount<=0)return;setStore(s=>({...s,bills:s.bills.map(x=>x.id===b.id?{...x,paid:Math.min(x.amount,x.paid+amount),status:x.paid+amount>=x.amount?"paid":"part-paid"}:x)}));postJournal(new Date().toISOString().slice(0,10),`Paid ${b.number}`,[{account:"Accounts Payable",side:"debit",amount},{account:"Bank",side:"credit",amount}],b.number)};
 const addRefund=(e:FormEvent)=>{e.preventDefault();if(!refund.customer||refund.amount<=0)return;setStore(s=>({...s,refunds:[{id:id("refund"),...refund,date:refund.date||new Date().toISOString().slice(0,10)},...s.refunds]}));postJournal(refund.date,"Customer refund",[{account:"Sales Returns",side:"debit",amount:refund.amount},{account:"Bank",side:"credit",amount:refund.amount}],refund.reference||"Refund");setRefund({reference:"",customer:"",amount:0,date:"",method:"Bank transfer"})};
 const printDoc=(d:Doc)=>{const t=calc(d.items);const w=window.open("","_blank","width=850,height=900");if(!w)return;w.document.write(`<html><head><title>${d.number}</title><style>body{font-family:Arial;padding:48px;color:#173244}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #ccd8de;text-align:left}.right{text-align:right}</style></head><body><h1>${d.kind.toUpperCase()} ${d.number}</h1><p>Customer: ${d.customer}<br>Date: ${d.date}<br>Due: ${d.due||"On receipt"}</p><table><tr><th>Description</th><th>Qty</th><th>Rate</th><th>Total</th></tr>${d.items.map(i=>`<tr><td>${i.description}</td><td>${i.qty}</td><td>${money(i.rate)}</td><td>${money(i.qty*i.rate)}</td></tr>`).join("")}</table><p class="right">GST ${money(t.gst)}<br><strong>Total ${money(t.total)}</strong><br>Paid ${money(d.payments)}<br>Balance ${money(Math.max(0,t.total-d.payments))}</p><p>${d.notes}</p><script>window.print()</script></body></html>`);w.document.close()};
 return <section className="advanced-accounting"><header><small>BUSINESS LIFELINE NATIVE FINANCE</small><h2>Double-entry accounting, documents, bills and payments</h2><p>Every posted transaction balances. Quotes, invoices, supplier bills, partial payments, credits and refunds stay connected.</p></header><nav>{([['dashboard','Dashboard'],['journals','Double-entry ledger'],['sales','Quotes & invoices'],['bills','Supplier bills'],['payments','Payments & refunds'],['reports','Reports & GST']] as const).map(([k,l])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}>{l}</button>)}</nav>
 {tab==="dashboard"&&<main><div className="aa-kpis"><article><small>Sales</small><strong>{money(sales)}</strong></article><article><small>Accounts receivable</small><strong>{money(ar)}</strong></article><article><small>Accounts payable</small><strong>{money(ap)}</strong></article><article><small>Estimated GST payable</small><strong>{money(gstCollected-gstCredits)}</strong></article></div><section><h3>Period lock</h3><p>Prevent accidental posting before a reviewed date.</p><input type="date" value={store.lockDate} onChange={e=>setStore(s=>({...s,lockDate:e.target.value}))}/></section></main>}
 {tab==="journals"&&<main><form onSubmit={addJournal} className="aa-form"><input type="date" value={journal.date} onChange={e=>setJournal({...journal,date:e.target.value})}/><input placeholder="Memo" value={journal.memo} onChange={e=>setJournal({...journal,memo:e.target.value})}/><input placeholder="Debit account" value={journal.debitAccount} onChange={e=>setJournal({...journal,debitAccount:e.target.value})}/><input placeholder="Credit account" value={journal.creditAccount} onChange={e=>setJournal({...journal,creditAccount:e.target.value})}/><input type="number" step="0.01" placeholder="Amount" value={journal.amount||''} onChange={e=>setJournal({...journal,amount:+e.target.value})}/><button>Post balanced journal</button></form><div className="aa-list">{store.journals.map(j=><article key={j.id}><strong>{j.date} · {j.memo}</strong>{j.lines.map((l,i)=><span key={i}>{l.side} {l.account}: {money(l.amount)}</span>)}<small>{j.source}</small></article>)}</div></main>}
 {tab==="sales"&&<main><form onSubmit={createDoc} className="aa-form"><select value={doc.kind} onChange={e=>setDoc({...doc,kind:e.target.value as Doc['kind']})}><option value="quote">Quote</option><option value="invoice">Invoice</option><option value="credit">Credit note</option></select><input placeholder="Customer" value={doc.customer} onChange={e=>setDoc({...doc,customer:e.target.value})}/><input type="date" value={doc.due} onChange={e=>setDoc({...doc,due:e.target.value})}/>{doc.items.map((i,n)=><div className="aa-line" key={n}><input placeholder="Description" value={i.description} onChange={e=>setDoc({...doc,items:doc.items.map((x,k)=>k===n?{...x,description:e.target.value}:x)})}/><input type="number" value={i.qty} onChange={e=>setDoc({...doc,items:doc.items.map((x,k)=>k===n?{...x,qty:+e.target.value}:x)})}/><input type="number" step="0.01" value={i.rate||''} onChange={e=>setDoc({...doc,items:doc.items.map((x,k)=>k===n?{...x,rate:+e.target.value}:x)})}/><select value={i.gst} onChange={e=>setDoc({...doc,items:doc.items.map((x,k)=>k===n?{...x,gst:e.target.value as Item['gst']}:x)})}><option value="gst">GST inclusive</option><option value="free">GST-free</option><option value="input">Input taxed</option></select></div>)}<button type="button" onClick={()=>setDoc({...doc,items:[...doc.items,{description:"",qty:1,rate:0,gst:"gst"}]})}>Add line</button><textarea placeholder="Notes" value={doc.notes} onChange={e=>setDoc({...doc,notes:e.target.value})}/><button>Create numbered document</button></form><div className="aa-list">{store.docs.map(d=><article key={d.id}><strong>{d.number} · {d.customer}</strong><span>{d.kind} · {d.status} · {money(calc(d.items).total)} · balance {money(Math.max(0,calc(d.items).total-d.payments))}</span><div><button onClick={()=>printDoc(d)}>Print/PDF</button>{d.kind==="invoice"&&d.status!=="paid"&&<button onClick={()=>recordDocPayment(d)}>Record payment</button>}</div></article>)}</div></main>}
 {tab==="bills"&&<main><form onSubmit={addBill} className="aa-form"><input placeholder="Supplier" value={bill.supplier} onChange={e=>setBill({...bill,supplier:e.target.value})}/><input placeholder="Bill number" value={bill.number} onChange={e=>setBill({...bill,number:e.target.value})}/><input type="date" value={bill.date} onChange={e=>setBill({...bill,date:e.target.value})}/><input type="date" value={bill.due} onChange={e=>setBill({...bill,due:e.target.value})}/><input type="number" step="0.01" placeholder="Total" value={bill.amount||''} onChange={e=>setBill({...bill,amount:+e.target.value})}/><input type="number" step="0.01" placeholder="GST credit" value={bill.gst||''} onChange={e=>setBill({...bill,gst:+e.target.value})}/><button>Add supplier bill</button></form><div className="aa-list">{store.bills.map(b=><article key={b.id}><strong>{b.number} · {b.supplier}</strong><span>{b.status} · total {money(b.amount)} · owing {money(b.amount-b.paid)}</span>{b.status!=="paid"&&<button onClick={()=>payBill(b)}>Record supplier payment</button>}</article>)}</div></main>}
 {tab==="payments"&&<main><form onSubmit={addRefund} className="aa-form"><h3>Record refund</h3><input placeholder="Customer" value={refund.customer} onChange={e=>setRefund({...refund,customer:e.target.value})}/><input placeholder="Reference" value={refund.reference} onChange={e=>setRefund({...refund,reference:e.target.value})}/><input type="number" step="0.01" placeholder="Amount" value={refund.amount||''} onChange={e=>setRefund({...refund,amount:+e.target.value})}/><input type="date" value={refund.date} onChange={e=>setRefund({...refund,date:e.target.value})}/><select value={refund.method} onChange={e=>setRefund({...refund,method:e.target.value})}><option>Bank transfer</option><option>Cash</option><option>Card reversal</option></select><button>Record refund and journal</button></form><div className="aa-list">{store.refunds.map(r=><article key={r.id}><strong>{r.customer} · {r.reference}</strong><span>{money(r.amount)} · {r.method} · {r.date}</span></article>)}</div></main>}
 {tab==="reports"&&<main><div className="aa-grid"><section><h3>Trial balance</h3>{trial.map(a=><p key={a.account}><strong>{a.account}</strong> debit {money(a.debit)} · credit {money(a.credit)} · balance {money(a.balance)}</p>)}</section><section><h3>GST operating summary</h3><p>GST collected: <strong>{money(gstCollected)}</strong></p><p>GST input credits: <strong>{money(gstCredits)}</strong></p><p>Estimated net GST: <strong>{money(gstCollected-gstCredits)}</strong></p><p className="note">Requires accountant or BAS-agent validation before lodgement.</p></section></div></main>}
 </section>;
}
