"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type View = "dashboard"|"crm"|"sales"|"market"|"jobs"|"stock"|"suppliers"|"money"|"team"|"reports";
type Customer={id:string;name:string;email:string;phone:string;stage:"lead"|"qualified"|"customer"|"inactive";value:number;nextAction:string;notes:string};
type Product={id:string;name:string;sku:string;barcode:string;qty:number;reorder:number;price:number;cost:number;supplierId:string};
type Quote={id:string;customerId:string;description:string;amount:number;status:"draft"|"sent"|"accepted"|"declined"};
type Job={id:string;customerId:string;description:string;status:"planned"|"active"|"complete";amount:number};
type Invoice={id:string;customerId:string;amount:number;status:"draft"|"sent"|"paid"|"overdue"};
type Sale={id:string;customerId?:string;items:{productId:string;name:string;qty:number;price:number}[];total:number;payment:string;channel:"counter"|"market";createdAt:string};
type Supplier={id:string;name:string;contact:string;terms:string};
type Expense={id:string;supplier:string;category:string;amount:number;date:string};
type Task={id:string;title:string;owner:string;due:string;done:boolean};
type MarketSession={open:boolean;opening:number;closing:number;expenses:number;startedAt:string};
type Store={customers:Customer[];products:Product[];quotes:Quote[];jobs:Job[];invoices:Invoice[];sales:Sale[];suppliers:Supplier[];expenses:Expense[];tasks:Task[];market:MarketSession};

const KEY="business-lifeline-operating-platform-v1";
const empty:Store={customers:[],products:[],quotes:[],jobs:[],invoices:[],sales:[],suppliers:[],expenses:[],tasks:[],market:{open:false,opening:0,closing:0,expenses:0,startedAt:""}};
const tabs:[View,string,string][]=[["dashboard","Command Centre","What needs attention now"],["crm","CRM & Pipeline","Leads, customers and follow-up"],["sales","Sales & POS","Quotes, invoices and counter sales"],["market","Market Sales","Fast mobile selling and cash close"],["jobs","Jobs & Delivery","Work from accepted quote to completion"],["stock","Products & Stock","Pricing, stock and reorder control"],["suppliers","Suppliers & Purchasing","Supplier records and reorder preparation"],["money","Money","Invoices, expenses and cash position"],["team","Team & Tasks","Ownership, work and due dates"],["reports","Reports","Sales, margin and operating health"]];
const id=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const money=(n:number)=>n.toLocaleString("en-AU",{style:"currency",currency:"AUD"});

export function BusinessOperatingPlatform(){
 const [view,setView]=useState<View>("dashboard"); const [store,setStore]=useState<Store>(empty); const [ready,setReady]=useState(false);
 const [customer,setCustomer]=useState({name:"",email:"",phone:"",value:0,nextAction:"",notes:""});
 const [product,setProduct]=useState({name:"",sku:"",barcode:"",qty:0,reorder:0,price:0,cost:0,supplierId:""});
 const [supplier,setSupplier]=useState({name:"",contact:"",terms:""});
 const [quote,setQuote]=useState({customerId:"",description:"",amount:0});
 const [expense,setExpense]=useState({supplier:"",category:"Operating",amount:0,date:""});
 const [task,setTask]=useState({title:"",owner:"",due:""});
 const [cart,setCart]=useState<Record<string,number>>({}); const [saleCustomer,setSaleCustomer]=useState(""); const [payment,setPayment]=useState("Card");
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setStore({...empty,...JSON.parse(raw)})}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify(store))},[store,ready]);
 const revenue=useMemo(()=>store.sales.reduce((s,x)=>s+x.total,0),[store.sales]);
 const cogs=useMemo(()=>store.sales.reduce((s,x)=>s+x.items.reduce((a,i)=>a+i.qty*(store.products.find(p=>p.id===i.productId)?.cost||0),0),0),[store.sales,store.products]);
 const outstanding=useMemo(()=>store.invoices.filter(i=>i.status!=="paid").reduce((s,i)=>s+i.amount,0),[store.invoices]);
 const low=store.products.filter(p=>p.qty<=p.reorder);
 const cartItems=store.products.filter(p=>cart[p.id]>0).map(p=>({...p,cartQty:cart[p.id]}));
 const cartTotal=cartItems.reduce((s,p)=>s+p.price*p.cartQty,0);
 const addCustomer=(e:FormEvent)=>{e.preventDefault();if(!customer.name.trim())return;setStore(s=>({...s,customers:[{id:id("customer"),...customer,name:customer.name.trim(),stage:"lead"},...s.customers]}));setCustomer({name:"",email:"",phone:"",value:0,nextAction:"",notes:""})};
 const addProduct=(e:FormEvent)=>{e.preventDefault();if(!product.name.trim())return;setStore(s=>({...s,products:[{id:id("product"),...product,name:product.name.trim()},...s.products]}));setProduct({name:"",sku:"",barcode:"",qty:0,reorder:0,price:0,cost:0,supplierId:""})};
 const addSupplier=(e:FormEvent)=>{e.preventDefault();if(!supplier.name.trim())return;setStore(s=>({...s,suppliers:[{id:id("supplier"),...supplier},...s.suppliers]}));setSupplier({name:"",contact:"",terms:""})};
 const addQuote=(e:FormEvent)=>{e.preventDefault();if(!quote.customerId||quote.amount<=0)return;setStore(s=>({...s,quotes:[{id:id("quote"),...quote,status:"draft"},...s.quotes]}));setQuote({customerId:"",description:"",amount:0})};
 const acceptQuote=(qid:string)=>setStore(s=>{const q=s.quotes.find(x=>x.id===qid);if(!q)return s;return {...s,quotes:s.quotes.map(x=>x.id===qid?{...x,status:"accepted"}:x),jobs:[{id:id("job"),customerId:q.customerId,description:q.description,status:"planned",amount:q.amount},...s.jobs],invoices:[{id:id("invoice"),customerId:q.customerId,amount:q.amount,status:"draft"},...s.invoices],customers:s.customers.map(c=>c.id===q.customerId?{...c,stage:"customer"}:c)}});
 const checkout=(channel:"counter"|"market")=>{if(!cartItems.length)return;const sale:Sale={id:id("sale"),customerId:saleCustomer||undefined,items:cartItems.map(p=>({productId:p.id,name:p.name,qty:p.cartQty,price:p.price})),total:cartTotal,payment,channel,createdAt:new Date().toISOString()};setStore(s=>({...s,sales:[sale,...s.sales],products:s.products.map(p=>({...p,qty:Math.max(0,p.qty-(cart[p.id]||0))})),customers:s.customers.map(c=>c.id===saleCustomer?{...c,stage:"customer",value:c.value+sale.total}:c)}));setCart({});setSaleCustomer("")};
 const addExpense=(e:FormEvent)=>{e.preventDefault();if(expense.amount<=0)return;setStore(s=>({...s,expenses:[{id:id("expense"),...expense},...s.expenses]}));setExpense({supplier:"",category:"Operating",amount:0,date:""})};
 const addTask=(e:FormEvent)=>{e.preventDefault();if(!task.title.trim())return;setStore(s=>({...s,tasks:[{id:id("task"),...task,done:false},...s.tasks]}));setTask({title:"",owner:"",due:""})};
 const customerName=(cid:string)=>store.customers.find(c=>c.id===cid)?.name||"Walk-in";
 return <section className="bos3">
  <header><div><small>BUSINESS OPERATING SYSTEM</small><h2>Run the whole business from one connected flow</h2><p>Lead → quote → job → invoice → payment, with stock, suppliers, market sales, expenses, tasks and reporting updating together.</p></div></header>
  <nav>{tabs.map(([k,l,d])=><button key={k} className={view===k?"active":""} onClick={()=>setView(k)}><strong>{l}</strong><small>{d}</small></button>)}</nav>
  {view==="dashboard"&&<main><div className="kpis"><article><small>Revenue</small><strong>{money(revenue)}</strong></article><article><small>Gross margin</small><strong>{money(revenue-cogs)}</strong></article><article><small>Outstanding</small><strong>{money(outstanding)}</strong></article><article><small>Low stock</small><strong>{low.length}</strong></article></div><div className="grid"><section><h3>Priority actions</h3>{low.map(p=><p key={p.id}>Reorder {p.name}: {p.qty} left</p>)}{store.invoices.filter(i=>i.status==="overdue").map(i=><p key={i.id}>Follow up overdue invoice for {customerName(i.customerId)}</p>)}{store.tasks.filter(t=>!t.done).slice(0,8).map(t=><p key={t.id}>{t.title} · {t.owner||"Unassigned"}</p>)}</section><section><h3>Sales pipeline</h3>{(["lead","qualified","customer"] as const).map(stage=><p key={stage}><strong>{stage}</strong> {store.customers.filter(c=>c.stage===stage).length}</p>)}</section></div></main>}
  {view==="crm"&&<main><form onSubmit={addCustomer} className="form"><h3>Add lead or customer</h3><input placeholder="Business or customer name" value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})}/><input placeholder="Email" value={customer.email} onChange={e=>setCustomer({...customer,email:e.target.value})}/><input placeholder="Phone" value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})}/><input placeholder="Next action" value={customer.nextAction} onChange={e=>setCustomer({...customer,nextAction:e.target.value})}/><textarea placeholder="Notes" value={customer.notes} onChange={e=>setCustomer({...customer,notes:e.target.value})}/><button>Add to CRM</button></form><div className="cards">{store.customers.map(c=><article key={c.id}><small>{c.stage.toUpperCase()}</small><h3>{c.name}</h3><p>{c.email} {c.phone}</p><p>Lifetime value: {money(c.value)}</p><p>Next: {c.nextAction||"Not set"}</p><div className="actions"><button onClick={()=>setStore(s=>({...s,customers:s.customers.map(x=>x.id===c.id?{...x,stage:x.stage==="lead"?"qualified":"customer"}:x)}))}>Advance stage</button><button onClick={()=>{setQuote({...quote,customerId:c.id});setView("sales")}}>Create quote</button></div></article>)}</div></main>}
  {view==="sales"&&<main><div className="grid"><form onSubmit={addQuote} className="form"><h3>Create quote</h3><select value={quote.customerId} onChange={e=>setQuote({...quote,customerId:e.target.value})}><option value="">Choose customer</option>{store.customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input placeholder="Work or sale description" value={quote.description} onChange={e=>setQuote({...quote,description:e.target.value})}/><input type="number" placeholder="Amount" value={quote.amount||""} onChange={e=>setQuote({...quote,amount:+e.target.value})}/><button>Create quote</button></form><section><h3>Counter POS</h3><div className="product-picker">{store.products.map(p=><button key={p.id} disabled={p.qty<1} onClick={()=>setCart({...cart,[p.id]:(cart[p.id]||0)+1})}>{p.name}<small>{money(p.price)} · {p.qty} left</small></button>)}</div><select value={saleCustomer} onChange={e=>setSaleCustomer(e.target.value)}><option value="">Walk-in customer</option>{store.customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={payment} onChange={e=>setPayment(e.target.value)}><option>Card</option><option>Cash</option><option>Bank transfer</option></select><p><strong>{cartItems.length} products · {money(cartTotal)}</strong></p><button onClick={()=>checkout("counter")}>Complete sale</button></section></div><h3>Quotes</h3><div className="cards">{store.quotes.map(q=><article key={q.id}><small>{q.status}</small><h3>{customerName(q.customerId)}</h3><p>{q.description}</p><strong>{money(q.amount)}</strong>{q.status!=="accepted"&&<button onClick={()=>acceptQuote(q.id)}>Accept → create job and invoice</button>}</article>)}</div></main>}
  {view==="market"&&<main><div className="grid"><section><h3>Market session</h3>{!store.market.open?<><input type="number" placeholder="Opening cash" onChange={e=>setStore(s=>({...s,market:{...s.market,opening:+e.target.value}}))}/><button onClick={()=>setStore(s=>({...s,market:{...s.market,open:true,startedAt:new Date().toISOString()}}))}>Open market day</button></>:<><p>Session open · {store.market.startedAt&&new Date(store.market.startedAt).toLocaleTimeString()}</p><input type="number" placeholder="Closing cash" value={store.market.closing||""} onChange={e=>setStore(s=>({...s,market:{...s.market,closing:+e.target.value}}))}/><input type="number" placeholder="Market expenses" value={store.market.expenses||""} onChange={e=>setStore(s=>({...s,market:{...s.market,expenses:+e.target.value}}))}/><button onClick={()=>setStore(s=>({...s,market:{...s.market,open:false}}))}>Close and reconcile</button></>}</section><section><h3>Fast market sale</h3><div className="product-picker">{store.products.map(p=><button key={p.id} onClick={()=>setCart({...cart,[p.id]:(cart[p.id]||0)+1})}>{p.name}<small>{money(p.price)}</small></button>)}</div><p><strong>Total {money(cartTotal)}</strong></p><button disabled={!store.market.open} onClick={()=>checkout("market")}>Take payment</button></section></div><section><h3>Market reconciliation</h3><p>Market sales: {money(store.sales.filter(s=>s.channel==="market").reduce((a,s)=>a+s.total,0))}</p><p>Expected cash: {money(store.market.opening+store.sales.filter(s=>s.channel==="market"&&s.payment==="Cash").reduce((a,s)=>a+s.total,0)-store.market.expenses)}</p><p>Actual closing cash: {money(store.market.closing)}</p></section></main>}
  {view==="jobs"&&<main><div className="cards">{store.jobs.map(j=><article key={j.id}><small>{j.status}</small><h3>{customerName(j.customerId)}</h3><p>{j.description}</p><strong>{money(j.amount)}</strong><button onClick={()=>setStore(s=>({...s,jobs:s.jobs.map(x=>x.id===j.id?{...x,status:x.status==="planned"?"active":"complete"}:x)}))}>Move to next stage</button></article>)}</div></main>}
  {view==="stock"&&<main><form onSubmit={addProduct} className="form wide"><h3>Add product or service</h3><input placeholder="Name" value={product.name} onChange={e=>setProduct({...product,name:e.target.value})}/><input placeholder="SKU" value={product.sku} onChange={e=>setProduct({...product,sku:e.target.value})}/><input placeholder="Barcode" value={product.barcode} onChange={e=>setProduct({...product,barcode:e.target.value})}/><input type="number" placeholder="Quantity" value={product.qty||""} onChange={e=>setProduct({...product,qty:+e.target.value})}/><input type="number" placeholder="Reorder point" value={product.reorder||""} onChange={e=>setProduct({...product,reorder:+e.target.value})}/><input type="number" placeholder="Sell price" value={product.price||""} onChange={e=>setProduct({...product,price:+e.target.value})}/><input type="number" placeholder="Cost price" value={product.cost||""} onChange={e=>setProduct({...product,cost:+e.target.value})}/><select value={product.supplierId} onChange={e=>setProduct({...product,supplierId:e.target.value})}><option value="">No supplier</option>{store.suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button>Add product</button></form><div className="cards">{store.products.map(p=><article key={p.id} className={p.qty<=p.reorder?"warning":""}><h3>{p.name}</h3><p>{p.sku} {p.barcode}</p><strong>{p.qty} in stock</strong><p>{money(p.price)} sell · {money(p.cost)} cost</p></article>)}</div></main>}
  {view==="suppliers"&&<main><form onSubmit={addSupplier} className="form"><h3>Add supplier</h3><input placeholder="Supplier name" value={supplier.name} onChange={e=>setSupplier({...supplier,name:e.target.value})}/><input placeholder="Contact" value={supplier.contact} onChange={e=>setSupplier({...supplier,contact:e.target.value})}/><input placeholder="Payment terms" value={supplier.terms} onChange={e=>setSupplier({...supplier,terms:e.target.value})}/><button>Add supplier</button></form><div className="cards">{store.suppliers.map(s=><article key={s.id}><h3>{s.name}</h3><p>{s.contact}</p><p>{s.terms}</p><p>{store.products.filter(p=>p.supplierId===s.id).length} linked products</p></article>)}</div></main>}
  {view==="money"&&<main><div className="grid"><section><h3>Invoices</h3>{store.invoices.map(i=><p key={i.id}>{customerName(i.customerId)} · {money(i.amount)} · {i.status} <button onClick={()=>setStore(s=>({...s,invoices:s.invoices.map(x=>x.id===i.id?{...x,status:x.status==="draft"?"sent":"paid"}:x)}))}>Advance</button></p>)}</section><form onSubmit={addExpense} className="form"><h3>Add expense</h3><input placeholder="Supplier" value={expense.supplier} onChange={e=>setExpense({...expense,supplier:e.target.value})}/><input placeholder="Category" value={expense.category} onChange={e=>setExpense({...expense,category:e.target.value})}/><input type="number" placeholder="Amount" value={expense.amount||""} onChange={e=>setExpense({...expense,amount:+e.target.value})}/><input type="date" value={expense.date} onChange={e=>setExpense({...expense,date:e.target.value})}/><button>Add expense</button></form></div></main>}
  {view==="team"&&<main><form onSubmit={addTask} className="form"><h3>Add task</h3><input placeholder="Task" value={task.title} onChange={e=>setTask({...task,title:e.target.value})}/><input placeholder="Owner" value={task.owner} onChange={e=>setTask({...task,owner:e.target.value})}/><input type="date" value={task.due} onChange={e=>setTask({...task,due:e.target.value})}/><button>Add task</button></form><div className="cards">{store.tasks.map(t=><article key={t.id}><h3>{t.title}</h3><p>{t.owner||"Unassigned"} · {t.due||"No due date"}</p><button onClick={()=>setStore(s=>({...s,tasks:s.tasks.map(x=>x.id===t.id?{...x,done:!x.done}:x)}))}>{t.done?"Reopen":"Complete"}</button></article>)}</div></main>}
  {view==="reports"&&<main><div className="kpis"><article><small>Total sales</small><strong>{money(revenue)}</strong></article><article><small>Gross profit</small><strong>{money(revenue-cogs)}</strong></article><article><small>Expenses</small><strong>{money(store.expenses.reduce((a,e)=>a+e.amount,0))}</strong></article><article><small>Net operating result</small><strong>{money(revenue-cogs-store.expenses.reduce((a,e)=>a+e.amount,0))}</strong></article></div><section><h3>Sales by channel</h3><p>Counter: {money(store.sales.filter(s=>s.channel==="counter").reduce((a,s)=>a+s.total,0))}</p><p>Market: {money(store.sales.filter(s=>s.channel==="market").reduce((a,s)=>a+s.total,0))}</p><p>Customers: {store.customers.length} · Jobs: {store.jobs.length} · Products: {store.products.length}</p></section></main>}
 </section>
}
