"use client";

import { ChangeEvent, useEffect, useMemo, useState } from "react";

type RecordMeta={id:string;name:string;type:string;size:number;category:string;source:string;hash:string;addedAt:string;status:"stored"|"linked";link?:string};
const META_KEY="business-lifeline-document-vault-v1";
const DB="business-lifeline-vault";
const STORE="files";
const categories=["Receipts","Invoices","Supplier bills","Contracts","Tax & BAS","Banking","Customers","Products","Staff","Other"];
const openDb=()=>new Promise<IDBDatabase>((resolve,reject)=>{const req=indexedDB.open(DB,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STORE))req.result.createObjectStore(STORE)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});
const saveBlob=async(id:string,file:File)=>{const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(file,id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()};
const getBlob=async(id:string)=>{const db=await openDb();const value=await new Promise<Blob|undefined>((resolve,reject)=>{const req=db.transaction(STORE).objectStore(STORE).get(id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});db.close();return value};
const delBlob=async(id:string)=>{const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()};
const hashFile=async(file:File)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",await file.arrayBuffer()))).map(b=>b.toString(16).padStart(2,"0")).join("");
const size=(n:number)=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;

export function DocumentVaultMigrationCentre(){
 const[records,setRecords]=useState<RecordMeta[]>([]);const[category,setCategory]=useState("Other");const[link,setLink]=useState("");const[notice,setNotice]=useState("");const[query,setQuery]=useState("");
 useEffect(()=>{try{setRecords(JSON.parse(localStorage.getItem(META_KEY)||"[]"))}catch{}},[]);
 useEffect(()=>{localStorage.setItem(META_KEY,JSON.stringify(records))},[records]);
 const filtered=useMemo(()=>records.filter(r=>`${r.name} ${r.category} ${r.source}`.toLowerCase().includes(query.toLowerCase())),[records,query]);
 const upload=async(e:ChangeEvent<HTMLInputElement>)=>{const files=[...(e.target.files||[])];if(!files.length)return;let added=0;for(const file of files){const hash=await hashFile(file);if(records.some(r=>r.hash===hash)){setNotice(`${file.name} already exists and was skipped.`);continue}const id=`file-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;await saveBlob(id,file);const meta:RecordMeta={id,name:file.name,type:file.type||file.name.split(".").pop()||"file",size:file.size,category,source:"upload",hash,addedAt:new Date().toISOString(),status:"stored"};setRecords(r=>[meta,...r]);added++}if(added)setNotice(`${added} file${added===1?"":"s"} stored in the local vault.`);e.target.value=""};
 const addLink=()=>{try{new URL(link)}catch{setNotice("Enter a complete https:// link.");return}const meta:RecordMeta={id:`link-${Date.now()}`,name:link,type:"link",size:0,category,source:"external system",hash:link,addedAt:new Date().toISOString(),status:"linked",link};setRecords(r=>[meta,...r]);setLink("");setNotice("External record link saved.")};
 const download=async(r:RecordMeta)=>{if(r.link){window.open(r.link,"_blank");return}const blob=await getBlob(r.id);if(!blob){setNotice("The file bytes are not on this device. Restore them from the source or future cloud vault.");return}const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=r.name;a.click();URL.revokeObjectURL(url)};
 const remove=async(r:RecordMeta)=>{if(r.status==="stored")await delBlob(r.id);setRecords(x=>x.filter(v=>v.id!==r.id));setNotice(`${r.name} removed from this device.`)};
 const exportManifest=()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),records},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="business-lifeline-vault-manifest.json";a.click();URL.revokeObjectURL(a.href)};
 return <section className="document-vault"><header><div><small>DOCUMENT VAULT & MIGRATION CENTRE</small><h2>Keep the full business record</h2><p>Store any file locally, keep source links, detect duplicates and prepare old-system data for structured migration.</p></div><strong>{records.length} records</strong></header>{notice&&<div className="vault-notice">{notice}<button onClick={()=>setNotice("")}>Dismiss</button></div>}<div className="vault-grid"><section><h3>Add files</h3><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select><label className="vault-upload">Upload files<input type="file" multiple onChange={upload}/></label><p>Accepts PDFs, images, spreadsheets, documents, ZIPs, exports and other business records.</p></section><section><h3>Link an old system or folder</h3><input placeholder="https://..." value={link} onChange={e=>setLink(e.target.value)}/><button onClick={addLink}>Save source link</button><p>Use this for Xero, MYOB, Square, Shopify, Drive, Dropbox or an archive location.</p></section></div><section><div className="vault-toolbar"><input placeholder="Search records" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={exportManifest}>Export manifest</button></div><div className="vault-list">{filtered.length?filtered.map(r=><article key={r.id}><div><small>{r.category} · {r.status}</small><strong>{r.name}</strong><span>{r.type} · {size(r.size)} · {new Date(r.addedAt).toLocaleString("en-AU")}</span><code>{r.hash.slice(0,16)}</code></div><div><button onClick={()=>download(r)}>{r.link?"Open":"Download"}</button><button onClick={()=>remove(r)}>Remove</button></div></article>):<p>No matching records.</p>}</div></section><p className="vault-warning">Files are stored in IndexedDB on this device. Metadata is included in the existing workspace backup, but binary files are not cloud-backed until Firebase Storage is enabled.</p></section>;
}
