"use client";

import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { onAuthStateChanged, type User } from "firebase/auth";
import { deleteObject, getBlob as getCloudBlob, ref, uploadBytes } from "firebase/storage";
import { firebaseAuth, firebaseStorage } from "@/lib/firebase-client";

type RecordMeta={id:string;name:string;type:string;size:number;category:string;source:string;hash:string;addedAt:string;status:"stored"|"linked";link?:string;cloudPath?:string;cloudStatus?:"local"|"uploading"|"backed-up"|"error"};
const META_KEY="business-lifeline-document-vault-v1";
const DB="business-lifeline-vault";
const STORE="files";
const MAX_FILE_SIZE=25*1024*1024;
const categories=["Receipts","Invoices","Supplier bills","Contracts","Tax & BAS","Banking","Customers","Products","Staff","Other"];
const openDb=()=>new Promise<IDBDatabase>((resolve,reject)=>{const req=indexedDB.open(DB,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STORE))req.result.createObjectStore(STORE)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});
const saveBlob=async(id:string,file:Blob)=>{const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(file,id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()};
const getBlob=async(id:string)=>{const db=await openDb();const value=await new Promise<Blob|undefined>((resolve,reject)=>{const req=db.transaction(STORE).objectStore(STORE).get(id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});db.close();return value};
const delBlob=async(id:string)=>{const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()};
const hashFile=async(file:Blob)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",await file.arrayBuffer()))).map(b=>b.toString(16).padStart(2,"0")).join("");
const size=(n:number)=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
const safeName=(name:string)=>name.replace(/[^a-zA-Z0-9._-]/g,"-").slice(-120);

export function DocumentVaultMigrationCentre(){
 const[records,setRecords]=useState<RecordMeta[]>([]);const[category,setCategory]=useState("Other");const[link,setLink]=useState("");const[notice,setNotice]=useState("");const[query,setQuery]=useState("");const[user,setUser]=useState<User|null>(null);const[busy,setBusy]=useState(false);
 useEffect(()=>{try{setRecords(JSON.parse(localStorage.getItem(META_KEY)||"[]"))}catch{}},[]);
 useEffect(()=>{localStorage.setItem(META_KEY,JSON.stringify(records))},[records]);
 useEffect(()=>firebaseAuth?onAuthStateChanged(firebaseAuth,setUser):undefined,[]);
 const filtered=useMemo(()=>records.filter(r=>`${r.name} ${r.category} ${r.source}`.toLowerCase().includes(query.toLowerCase())),[records,query]);
 const cloudUpload=async(meta:RecordMeta,blob:Blob,uid:string)=>{if(!firebaseStorage)throw new Error("Firebase Storage is not configured");const path=`userVault/${uid}/${meta.id}/${safeName(meta.name)}`;await uploadBytes(ref(firebaseStorage,path),blob,{contentType:meta.type||"application/octet-stream",customMetadata:{hash:meta.hash,category:meta.category,recordId:meta.id}});return path};
 const upload=async(e:ChangeEvent<HTMLInputElement>)=>{const files=[...(e.target.files||[])];if(!files.length)return;setBusy(true);let added=0;for(const file of files){if(file.size>MAX_FILE_SIZE){setNotice(`${file.name} is larger than the current 25 MB limit and was skipped.`);continue}const hash=await hashFile(file);if(records.some(r=>r.hash===hash)){setNotice(`${file.name} already exists and was skipped.`);continue}const id=`file-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;await saveBlob(id,file);let meta:RecordMeta={id,name:file.name,type:file.type||file.name.split(".").pop()||"file",size:file.size,category,source:"upload",hash,addedAt:new Date().toISOString(),status:"stored",cloudStatus:user?"uploading":"local"};setRecords(r=>[meta,...r]);if(user){try{const cloudPath=await cloudUpload(meta,file,user.uid);meta={...meta,cloudPath,cloudStatus:"backed-up"};setRecords(r=>r.map(x=>x.id===id?meta:x))}catch{setRecords(r=>r.map(x=>x.id===id?{...x,cloudStatus:"error"}:x));setNotice(`${file.name} is safe on this device, but cloud backup failed. Check Firebase Storage setup.`)}}added++}if(added&&!notice)setNotice(`${added} file${added===1?"":"s"} stored${user?" and queued for secure cloud backup":" on this device"}.`);setBusy(false);e.target.value=""};
 const backupLocal=async()=>{if(!user||!firebaseStorage){setNotice("Sign in and enable Firebase Storage before backing up files.");return}setBusy(true);let backed=0;for(const record of records.filter(r=>r.status==="stored"&&!r.cloudPath)){const blob=await getBlob(record.id);if(!blob)continue;setRecords(x=>x.map(v=>v.id===record.id?{...v,cloudStatus:"uploading"}:v));try{const cloudPath=await cloudUpload(record,blob,user.uid);setRecords(x=>x.map(v=>v.id===record.id?{...v,cloudPath,cloudStatus:"backed-up"}:v));backed++}catch{setRecords(x=>x.map(v=>v.id===record.id?{...v,cloudStatus:"error"}:v))}}setBusy(false);setNotice(`${backed} local file${backed===1?"":"s"} backed up to the signed-in vault.`)};
 const addLink=()=>{try{new URL(link)}catch{setNotice("Enter a complete https:// link.");return}const meta:RecordMeta={id:`link-${Date.now()}`,name:link,type:"link",size:0,category,source:"external system",hash:link,addedAt:new Date().toISOString(),status:"linked",link,cloudStatus:"backed-up"};setRecords(r=>[meta,...r]);setLink("");setNotice("External record link saved.")};
 const download=async(r:RecordMeta)=>{if(r.link){window.open(r.link,"_blank");return}let blob=await getBlob(r.id);if(!blob&&r.cloudPath&&firebaseStorage&&user){try{blob=await getCloudBlob(ref(firebaseStorage,r.cloudPath));await saveBlob(r.id,blob);setNotice(`${r.name} restored to this device from the cloud vault.`)}catch{setNotice("Cloud restore failed. Confirm you are signed into the owner account and Storage rules are published.");return}}if(!blob){setNotice("The file bytes are not on this device or in the signed-in cloud vault.");return}const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=r.name;a.click();URL.revokeObjectURL(url)};
 const remove=async(r:RecordMeta)=>{if(r.status==="stored")await delBlob(r.id);if(r.cloudPath&&firebaseStorage&&user){try{await deleteObject(ref(firebaseStorage,r.cloudPath))}catch{setNotice("The local record was removed, but cloud deletion could not be confirmed.")}}setRecords(x=>x.filter(v=>v.id!==r.id));setNotice(`${r.name} removed.`)};
 const exportManifest=()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),records},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="business-lifeline-vault-manifest.json";a.click();URL.revokeObjectURL(a.href)};
 const cloudCount=records.filter(r=>r.cloudStatus==="backed-up"&&r.status==="stored").length;
 return <section className="document-vault"><header><div><small>DOCUMENT VAULT & MIGRATION CENTRE</small><h2>Keep the full business record on every device</h2><p>Store any file locally, detect duplicates and securely back up signed-in records through Firebase Storage.</p></div><strong>{records.length} records · {cloudCount} cloud</strong></header>{notice&&<div className="vault-notice">{notice}<button onClick={()=>setNotice("")}>Dismiss</button></div>}<div className="vault-grid"><section><h3>Add files</h3><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select><label className="vault-upload">{busy?"Working…":"Upload files"}<input type="file" multiple disabled={busy} onChange={upload}/></label><p>PDFs, photos, spreadsheets, documents, ZIPs and exports up to 25 MB each.</p>{user?<button disabled={busy} onClick={backupLocal}>Back up local files now</button>:<p><strong>Sign in to back up and restore files across devices.</strong></p>}</section><section><h3>Link an old system or folder</h3><input placeholder="https://..." value={link} onChange={e=>setLink(e.target.value)}/><button onClick={addLink}>Save source link</button><p>Use this for Xero, MYOB, Square, Shopify, Drive, Dropbox or an archive location.</p></section></div><section><div className="vault-toolbar"><input placeholder="Search records" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={exportManifest}>Export manifest</button></div><div className="vault-list">{filtered.length?filtered.map(r=><article key={r.id}><div><small>{r.category} · {r.status} · {r.cloudPath?"cloud backed":r.cloudStatus==="error"?"cloud error":"this device"}</small><strong>{r.name}</strong><span>{r.type} · {size(r.size)} · {new Date(r.addedAt).toLocaleString("en-AU")}</span><code>{r.hash.slice(0,16)}</code></div><div><button onClick={()=>download(r)}>{r.link?"Open":"Download / restore"}</button><button onClick={()=>remove(r)}>Remove</button></div></article>):<p>No matching records.</p>}</div></section><p className="vault-warning">Signed-in file bytes use owner-scoped Firebase Storage paths. Publish the repository storage.rules before relying on cloud backup. Local IndexedDB remains the offline copy.</p></section>;
}
