"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { createEmptyCrmStore, pipelineForecast, opportunityProbability, type CrmActivity, type CrmContact, type CrmOpportunity, type CrmStore } from "@/lib/lifeline-crm";

const KEY="business-lifeline-crm-v1";
type View="overview"|"companies"|"contacts"|"pipeline"|"tasks";
const iso=()=>new Date().toISOString();
const id=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
function load():CrmStore{
  const blank=createEmptyCrmStore();
  try{
    const raw=localStorage.getItem(KEY); if(raw) return {...blank,...JSON.parse(raw)};
    const old=JSON.parse(localStorage.getItem("business-lifeline-operating-system-v1")||"null");
    if(!old?.contacts) return blank;
    for(const item of old.contacts){
      const accountId=id("account");
      blank.accounts.push({id:accountId,name:item.name,type:item.type==="Customer"?"customer":item.type==="Supplier"?"supplier":"partner",tags:[item.type],customFields:{legacyValue:Number(item.value||0)},createdAt:iso(),updatedAt:iso()});
      if(item.nextAction) blank.tasks.push({id:id("task"),accountId,title:item.nextAction,priority:"normal",status:"open",createdAt:iso()});
    }
    return blank;
  }catch{return blank}
}
const money=(n:number,country:string)=>new Intl.NumberFormat("en-AU",{style:"currency",currency:country.toLowerCase().includes("australia")?"AUD":"USD",maximumFractionDigits:0}).format(n);
export function LifelineCrmWorkspace({country}:{country:string}){
 const [store,setStore]=useState<CrmStore>(createEmptyCrmStore()); const [view,setView]=useState<View>("overview"); const [ready,setReady]=useState(false);
 const [company,setCompany]=useState(""); const [contact,setContact]=useState({firstName:"",lastName:"",email:"",phone:"",accountId:""});
 const [deal,setDeal]=useState({accountId:"",title:"",value:0,expectedCloseDate:""}); const [note,setNote]=useState("");
 useEffect(()=>{setStore(load());setReady(true)},[]); useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify(store))},[store,ready]);
 const forecast=useMemo(()=>pipelineForecast(store),[store]); const pipeline=store.pipelines[0]; const openTasks=store.tasks.filter(t=>t.status==="open");
 const selectedAccount=store.accounts[0];
 const addCompany=(e:FormEvent)=>{e.preventDefault();if(!company.trim())return;const now=iso();setStore(s=>({...s,accounts:[{id:id("account"),name:company.trim(),type:"prospect",tags:[],customFields:{},createdAt:now,updatedAt:now},...s.accounts]}));setCompany("")};
 const addContact=(e:FormEvent)=>{e.preventDefault();if(!contact.firstName.trim()&&!contact.lastName.trim())return;const now=iso();const c:CrmContact={id:id("contact"),...contact,firstName:contact.firstName.trim(),lastName:contact.lastName.trim(),tags:[],customFields:{},createdAt:now,updatedAt:now};setStore(s=>({...s,contacts:[c,...s.contacts]}));setContact({firstName:"",lastName:"",email:"",phone:"",accountId:""})};
 const addDeal=(e:FormEvent)=>{e.preventDefault();if(!deal.accountId||!deal.title.trim()||deal.value<0)return;const now=iso();const o:CrmOpportunity={id:id("deal"),accountId:deal.accountId,pipelineId:pipeline.id,stageId:pipeline.stages[0].id,title:deal.title.trim(),value:deal.value,expectedCloseDate:deal.expectedCloseDate||undefined,createdAt:now,updatedAt:now};setStore(s=>({...s,opportunities:[o,...s.opportunities]}));setDeal({accountId:"",title:"",value:0,expectedCloseDate:""})};
 const move=(o:CrmOpportunity,stageId:string)=>setStore(s=>({...s,opportunities:s.opportunities.map(x=>x.id===o.id?{...x,stageId,updatedAt:iso()}:x),activities:[{id:id("activity"),type:"system",accountId:o.accountId,opportunityId:o.id,subject:`${o.title} moved to ${pipeline.stages.find(x=>x.id===stageId)?.name}`,occurredAt:iso(),createdAt:iso()},...s.activities]}));
 const addNote=()=>{if(!selectedAccount||!note.trim())return;const a:CrmActivity={id:id("activity"),type:"note",accountId:selectedAccount.id,subject:note.trim(),occurredAt:iso(),createdAt:iso()};setStore(s=>({...s,activities:[a,...s.activities]}));setNote("")};
 return <section className="crm-workspace">
  <header className="crm-hero"><div><span>BUSINESS LIFELINE CRM</span><h4>Customers, opportunities and follow-ups</h4><p>Know who you are dealing with, what work may be coming, what it is worth and what needs to happen next.</p></div><button className="button primary" onClick={()=>setView("pipeline")}>Open pipeline</button></header>
  <nav className="crm-nav">{(["overview","companies","contacts","pipeline","tasks"] as View[]).map(x=><button key={x} className={view===x?"active":""} onClick={()=>setView(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</nav>
  {view==="overview"&&<><div className="crm-kpis"><article><strong>{store.accounts.length}</strong><span>Companies</span></article><article><strong>{store.contacts.length}</strong><span>Contacts</span></article><article><strong>{store.opportunities.filter(o=>!["won","lost"].includes(o.stageId)).length}</strong><span>Open deals</span></article><article><strong>{money(forecast.weighted,country)}</strong><span>Weighted pipeline</span></article><article><strong>{openTasks.length}</strong><span>Open tasks</span></article></div><div className="crm-explainer"><strong>How to use this CRM</strong><p>1. Add a company. 2. Add the people you speak to. 3. Create an opportunity when there is potential work. 4. Move the opportunity across the pipeline as it progresses. 5. Use Tasks and notes so the next action is never forgotten.</p></div>{selectedAccount&&<div className="crm-timeline"><div><strong>Recent activity · {selectedAccount.name}</strong><div className="crm-note"><input placeholder="Add a note about this relationship…" value={note} onChange={e=>setNote(e.target.value)}/><button onClick={addNote}>Add note</button></div></div>{store.activities.filter(a=>a.accountId===selectedAccount.id).slice(0,8).map(a=><article key={a.id}><b>{a.type}</b><span>{a.subject}</span><small>{new Date(a.occurredAt).toLocaleString()}</small></article>)}</div>}</>}
  {view==="companies"&&<div className="crm-two"><form onSubmit={addCompany} className="crm-form"><h5>Add company</h5><label>Company / customer name<input value={company} onChange={e=>setCompany(e.target.value)} placeholder="Example: Corr Plumbing"/></label><button className="button primary">Add company</button></form><div className="crm-list"><h5>Companies</h5>{store.accounts.length===0?<p>No companies yet. Add your first customer or prospect.</p>:store.accounts.map(a=><article key={a.id}><div><strong>{a.name}</strong><span>{a.type} · {store.contacts.filter(c=>c.accountId===a.id).length} contacts</span></div><b>{store.opportunities.filter(o=>o.accountId===a.id).length} deals</b></article>)}</div></div>}
  {view==="contacts"&&<div className="crm-two"><form onSubmit={addContact} className="crm-form"><h5>Add contact</h5><label>First name<input value={contact.firstName} onChange={e=>setContact({...contact,firstName:e.target.value})}/></label><label>Last name<input value={contact.lastName} onChange={e=>setContact({...contact,lastName:e.target.value})}/></label><label>Company<select value={contact.accountId} onChange={e=>setContact({...contact,accountId:e.target.value})}><option value="">No company</option>{store.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Email<input type="email" value={contact.email} onChange={e=>setContact({...contact,email:e.target.value})}/></label><label>Phone<input value={contact.phone} onChange={e=>setContact({...contact,phone:e.target.value})}/></label><button className="button primary">Add contact</button></form><div className="crm-list"><h5>People</h5>{store.contacts.map(c=><article key={c.id}><div><strong>{c.firstName} {c.lastName}</strong><span>{store.accounts.find(a=>a.id===c.accountId)?.name||"Independent"} · {c.email||c.phone||"No contact details"}</span></div></article>)}</div></div>}
  {view==="pipeline"&&<><form onSubmit={addDeal} className="crm-deal-form"><select value={deal.accountId} onChange={e=>setDeal({...deal,accountId:e.target.value})} required><option value="">Choose company</option>{store.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><input placeholder="Opportunity / work" value={deal.title} onChange={e=>setDeal({...deal,title:e.target.value})} required/><input type="number" min="0" placeholder="Value" value={deal.value||""} onChange={e=>setDeal({...deal,value:Number(e.target.value)})}/><input type="date" value={deal.expectedCloseDate} onChange={e=>setDeal({...deal,expectedCloseDate:e.target.value})}/><button className="button primary">Add opportunity</button></form><div className="crm-board">{pipeline.stages.map(stage=><section key={stage.id}><header><strong>{stage.name}</strong><span>{stage.probability}%</span></header>{store.opportunities.filter(o=>o.stageId===stage.id).map(o=><article key={o.id}><strong>{o.title}</strong><span>{store.accounts.find(a=>a.id===o.accountId)?.name}</span><b>{money(o.value,country)}</b><small>Weighted {money(o.value*opportunityProbability(o,store.pipelines)/100,country)}</small><select value={o.stageId} onChange={e=>move(o,e.target.value)}>{pipeline.stages.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></article>)}</section>)}</div></>}
  {view==="tasks"&&<div className="crm-list"><div className="crm-section-title"><h5>Follow-ups</h5><span>{openTasks.length} open</span></div>{openTasks.length===0?<p>No open follow-ups. Tasks are created from migrated follow-ups and can be expanded as you work.</p>:openTasks.map(t=><article key={t.id}><div><strong>{t.title}</strong><span>{store.accounts.find(a=>a.id===t.accountId)?.name||"Unassigned"} {t.dueAt?"· "+new Date(t.dueAt).toLocaleDateString():""}</span></div><button onClick={()=>setStore(s=>({...s,tasks:s.tasks.map(x=>x.id===t.id?{...x,status:"done",completedAt:iso()}:x)}))}>Complete</button></article>)}</div>}
 </section>
}