"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import { INDUSTRY_CAPABILITIES, documentSubtotal, projectEconomics, receivePurchaseOrder, transferStock, type IndustryPack, type OperatingStore, type Project, type PurchaseOrder, type ServiceOrder, type ProductionOrder } from "@/lib/lifeline-operations";
type View="home"|"projects"|"purchasing"|"inventory"|"service"|"manufacturing";
const KEY="business-lifeline-operations-v1"; const iso=()=>new Date().toISOString(); const uid=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,6)}`;
const blank=(pack:IndustryPack="trades"):OperatingStore=>({industryPack:pack,locations:[{id:"main",name:"Main location",type:"warehouse",active:true}],inventory:[],movements:[],salesOrders:[],purchaseOrders:[],projects:[],projectTasks:[],variations:[],progressClaims:[],serviceAgreements:[],serviceOrders:[],boms:[],routings:[],workCentres:[],productionOrders:[]});
function load(){try{const r=localStorage.getItem(KEY);return r?{...blank(),...JSON.parse(r)}:blank()}catch{return blank()}}
export function LifelineOperationsWorkspace(){
 const [s,setS]=useState<OperatingStore>(blank());const [ready,setReady]=useState(false);const [view,setView]=useState<View>("home");
 const [project,setProject]=useState({accountId:"",name:"",budgetRevenue:0,budgetCost:0,dueAt:""});
 const [po,setPo]=useState({supplierAccountId:"",description:"",quantity:1,unitPrice:0});
 const [stock,setStock]=useState({productId:"",onHand:0,averageCost:0});
 const [service,setService]=useState({accountId:"",site:"",scheduledStart:""});
 const [production,setProduction]=useState({productId:"",quantity:1});
 useEffect(()=>{setS(load());setReady(true)},[]);useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify(s))},[s,ready]);
 const money=(n:number)=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD",maximumFractionDigits:0}).format(n);
 const capabilities=INDUSTRY_CAPABILITIES[s.industryPack];const stockUnits=s.inventory.reduce((a,b)=>a+b.onHand,0);
 const createProject=(e:FormEvent)=>{e.preventDefault();if(!project.name.trim())return;const now=iso();const p:Project={id:uid("project"),accountId:project.accountId||"direct",name:project.name,status:"planned",budgetRevenue:project.budgetRevenue,budgetCost:project.budgetCost,dueAt:project.dueAt||undefined,createdAt:now,updatedAt:now};setS(x=>({...x,projects:[p,...x.projects]}));setProject({accountId:"",name:"",budgetRevenue:0,budgetCost:0,dueAt:""})};
 const createPo=(e:FormEvent)=>{e.preventDefault();if(!po.supplierAccountId.trim()||!po.description.trim())return;const now=iso();const line={id:uid("line"),description:po.description,quantity:po.quantity,unitPrice:po.unitPrice,taxRate:.1};const p:PurchaseOrder={id:uid("po"),supplierAccountId:po.supplierAccountId,status:"ordered",lines:[line],locationId:"main",received:{},orderedAt:now,createdAt:now,updatedAt:now};setS(x=>({...x,purchaseOrders:[p,...x.purchaseOrders]}));setPo({supplierAccountId:"",description:"",quantity:1,unitPrice:0})};
 const receive=(p:PurchaseOrder)=>setS(x=>({...x,purchaseOrders:x.purchaseOrders.map(o=>o.id===p.id?receivePurchaseOrder(o,Object.fromEntries(o.lines.map(l=>[l.id,Math.max(0,l.quantity-(o.received[l.id]||0))])),iso()):o)}));
 const addStock=(e:FormEvent)=>{e.preventDefault();if(!stock.productId.trim())return;setS(x=>({...x,inventory:[...x.inventory.filter(i=>!(i.productId===stock.productId&&i.locationId==="main")),{productId:stock.productId,locationId:"main",onHand:stock.onHand,allocated:0,available:stock.onHand,averageCost:stock.averageCost}]}));setStock({productId:"",onHand:0,averageCost:0})};
 const createService=(e:FormEvent)=>{e.preventDefault();if(!service.accountId.trim())return;const o:ServiceOrder={id:uid("service"),accountId:service.accountId,site:service.site,status:"planned",scheduledStart:service.scheduledStart||undefined,assignedTo:[],parts:{},labourHours:0,createdAt:iso()};setS(x=>({...x,serviceOrders:[o,...x.serviceOrders]}));setService({accountId:"",site:"",scheduledStart:""})};
 const createProduction=(e:FormEvent)=>{e.preventDefault();if(!production.productId.trim())return;const o:ProductionOrder={id:uid("production"),productId:production.productId,quantity:production.quantity,bomId:"unassigned",status:"planned",consumed:{},outputQuantity:0,createdAt:iso()};setS(x=>({...x,productionOrders:[o,...x.productionOrders]}));setProduction({productId:"",quantity:1})};
 const projectValue=useMemo(()=>s.projects.reduce((n,p)=>n+projectEconomics(p,s.projectTasks,s.variations).budgetRevenue,0),[s]);
 return <section className="phase-one-ops">
  <header className="p1-hero"><div><small>LIFELINE OPERATIONS · PHASE 1</small><h2>Run the work after the sale</h2><p>Projects, purchasing, stock, service and production share one operating model instead of separate spreadsheets.</p></div><label>Business type<select value={s.industryPack} onChange={e=>setS(x=>({...x,industryPack:e.target.value as IndustryPack}))}>{Object.keys(INDUSTRY_CAPABILITIES).map(x=><option key={x}>{x}</option>)}</select></label></header>
  <nav className="p1-nav">{(["home","projects","purchasing","inventory","service","manufacturing"] as View[]).map(x=><button className={view===x?"active":""} key={x} onClick={()=>setView(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</nav>
  {view==="home"&&<><div className="p1-kpis"><article><b>{s.projects.filter(x=>x.status!=="complete").length}</b><span>Open projects</span></article><article><b>{money(projectValue)}</b><span>Project value</span></article><article><b>{s.purchaseOrders.filter(x=>x.status!=="received").length}</b><span>POs to receive</span></article><article><b>{stockUnits}</b><span>Units on hand</span></article><article><b>{s.serviceOrders.filter(x=>x.status!=="complete").length}</b><span>Service orders</span></article></div><div className="p1-cap"><strong>Enabled for {s.industryPack}</strong><div>{capabilities.map(x=><span key={x}>{x.replaceAll("-"," ")}</span>)}</div></div></>}
  {view==="projects"&&<div className="p1-grid"><form onSubmit={createProject} className="p1-form"><h3>New project / job</h3><input placeholder="Customer/account" value={project.accountId} onChange={e=>setProject({...project,accountId:e.target.value})}/><input required placeholder="Project / job name" value={project.name} onChange={e=>setProject({...project,name:e.target.value})}/><input type="number" min="0" placeholder="Revenue budget" value={project.budgetRevenue||""} onChange={e=>setProject({...project,budgetRevenue:Number(e.target.value)})}/><input type="number" min="0" placeholder="Cost budget" value={project.budgetCost||""} onChange={e=>setProject({...project,budgetCost:Number(e.target.value)})}/><input type="date" value={project.dueAt} onChange={e=>setProject({...project,dueAt:e.target.value})}/><button>Create project</button></form><div className="p1-list">{s.projects.map(p=>{const e=projectEconomics(p,s.projectTasks,s.variations);return <article key={p.id}><div><strong>{p.name}</strong><span>{p.accountId} · {p.status}</span></div><div><b>{money(e.budgetRevenue)}</b><small>Budget cost {money(e.budgetCost)} · Forecast margin {money(e.forecastMargin)}</small></div><select value={p.status} onChange={ev=>setS(x=>({...x,projects:x.projects.map(y=>y.id===p.id?{...y,status:ev.target.value as Project["status"],updatedAt:iso()}:y)}))}>{["planned","scheduled","active","blocked","complete","cancelled"].map(z=><option key={z}>{z}</option>)}</select></article>})}</div></div>}
  {view==="purchasing"&&<div className="p1-grid"><form onSubmit={createPo} className="p1-form"><h3>New purchase order</h3><input required placeholder="Supplier" value={po.supplierAccountId} onChange={e=>setPo({...po,supplierAccountId:e.target.value})}/><input required placeholder="Item / service" value={po.description} onChange={e=>setPo({...po,description:e.target.value})}/><input type="number" min="0.01" step=".01" value={po.quantity} onChange={e=>setPo({...po,quantity:Number(e.target.value)})}/><input type="number" min="0" step=".01" placeholder="Unit cost" value={po.unitPrice||""} onChange={e=>setPo({...po,unitPrice:Number(e.target.value)})}/><button>Create PO</button></form><div className="p1-list">{s.purchaseOrders.map(p=><article key={p.id}><div><strong>{p.supplierAccountId}</strong><span>{p.status} · {p.lines.map(l=>l.description).join(", ")}</span></div><b>{money(documentSubtotal(p.lines))}</b>{p.status!=="received"&&<button onClick={()=>receive(p)}>Receive remaining</button>}</article>)}</div></div>}
  {view==="inventory"&&<div className="p1-grid"><form onSubmit={addStock} className="p1-form"><h3>Add / adjust stock</h3><input required placeholder="Product / SKU" value={stock.productId} onChange={e=>setStock({...stock,productId:e.target.value})}/><input type="number" min="0" placeholder="On hand" value={stock.onHand||""} onChange={e=>setStock({...stock,onHand:Number(e.target.value)})}/><input type="number" min="0" step=".01" placeholder="Average cost" value={stock.averageCost||""} onChange={e=>setStock({...stock,averageCost:Number(e.target.value)})}/><button>Save stock</button></form><div className="p1-list">{s.inventory.map(i=><article key={i.productId+i.locationId}><div><strong>{i.productId}</strong><span>{s.locations.find(l=>l.id===i.locationId)?.name} · {i.available} available</span></div><b>{i.onHand} on hand</b><small>{money(i.averageCost)} avg cost</small></article>)}</div></div>}
  {view==="service"&&<div className="p1-grid"><form onSubmit={createService} className="p1-form"><h3>New service order</h3><input required placeholder="Customer/account" value={service.accountId} onChange={e=>setService({...service,accountId:e.target.value})}/><input placeholder="Site / address" value={service.site} onChange={e=>setService({...service,site:e.target.value})}/><input type="datetime-local" value={service.scheduledStart} onChange={e=>setService({...service,scheduledStart:e.target.value})}/><button>Create service order</button></form><div className="p1-list">{s.serviceOrders.map(o=><article key={o.id}><div><strong>{o.accountId}</strong><span>{o.site||"No site"} · {o.status}</span></div><select value={o.status} onChange={e=>setS(x=>({...x,serviceOrders:x.serviceOrders.map(y=>y.id===o.id?{...y,status:e.target.value as ServiceOrder["status"]}:y)}))}>{["planned","scheduled","active","blocked","complete","cancelled"].map(z=><option key={z}>{z}</option>)}</select></article>)}</div></div>}
  {view==="manufacturing"&&<div className="p1-grid"><form onSubmit={createProduction} className="p1-form"><h3>New production order</h3><input required placeholder="Finished product / SKU" value={production.productId} onChange={e=>setProduction({...production,productId:e.target.value})}/><input type="number" min="1" value={production.quantity} onChange={e=>setProduction({...production,quantity:Number(e.target.value)})}/><button>Create production order</button><p>BOM/routing assignment is required before release. This prevents an unconfigured production order from consuming stock.</p></form><div className="p1-list">{s.productionOrders.map(o=><article key={o.id}><div><strong>{o.productId}</strong><span>{o.quantity} units · {o.status}</span></div><b>{o.bomId==="unassigned"?"BOM required":o.bomId}</b></article>)}</div></div>}
 </section>
}