"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Entry={id:string;date:string;type:"income"|"expense"|"asset"|"liability";account:string;description:string;amount:number;source:string};
type Payment={id:string;customer:string;reference:string;amount:number;method:string;date:string};
type Profile={name:string;abn:string;email:string;phone:string;address:string;gstRegistered:boolean;gstInclusive:boolean;paymentTerms:number};
type Provider={id:string;label:string;category:string;mode:"internal"|"external"|"planned";provider:string};
type Store={profile:Profile;entries:Entry[];payments:Payment[];providers:Provider[]};

const KEY="business-lifeline-native-finance-v1";
const OPS_KEY="business-lifeline-operating-platform-v1";
const empty:Store={profile:{name:"",abn:"",email:"",phone:"",address:"",gstRegistered:false,gstInclusive:true,paymentTerms:14},entries:[],payments:[],providers:[
 {id:"payments",label:"Payments",category:"Money movement",mode:"planned",provider:"Stripe or Square adapter"},
 {id:"accounting",label:"Accounting export",category:"Books and tax",mode:"internal",provider:"Business Lifeline native ledger"},
 {id:"email",label:"Email delivery",category:"Communications",mode:"planned",provider:"Resend/Postmark adapter"},
 {id:"sms",label:"SMS delivery",category:"Communications",mode:"planned",provider:"Twilio adapter"},
 {id:"banking",label:"Bank feeds",category:"Banking",mode:"planned",provider:"Open Banking adapter"},
 {id:"documents",label:"Documents",category:"Storage",mode:"internal",provider:"Business Lifeline records"},
 {id:"monitoring",label:"Error monitoring",category:"Reliability",mode:"planned",provider:"Sentry adapter"},
 {id:"analytics",label:"Product analytics",category:"Insights",mode:"internal",provider:"Privacy-first internal events"},
]};
const id=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const money=(n:number)=>n.toLocaleString("en-AU",{style:"currency",currency:"AUD"});

export function NativeFinanceHub(){
 const [store,setStore]=useState<Store>(empty); const [ready,setReady]=useState(false); const [tab,setTab]=useState<"overview"|"ledger"|"documents"|"payments"|"providers">("overview");
 const [entry,setEntry]=useState({date:"",type:"income" as Entry["type"],account:"Sales",description:"",amount:0});
 const [payment,setPayment]=useState({customer:"",reference:"",amount:0,method:"Bank transfer",date:""});
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setStore({...empty,...JSON.parse(raw)})}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify(store))},[store,ready]);
 const imported=useMemo(()=>{try{const raw=localStorage.getItem(OPS_KEY);if(!raw)return {sales:0,expenses:0,invoices:0};const data=JSON.parse(raw);return {sales:(data.sales||[]).reduce((s:number,x:{total:number})=>s+(x.total||0),0),expenses:(data.expenses||[]).reduce((s:number,x:{amount:number})=>s+(x.amount||0),0),invoices:(data.invoices||[]).filter((x:{status:string})=>x.status!=="paid").reduce((s:number,x:{amount:number})=>s+(x.amount||0),0)}}catch{return {sales:0,expenses:0,invoices:0}}},[tab]);
 const totals=useMemo(()=>{const income=store.entries.filter(x=>x.type==="income").reduce((s,x)=>s+x.amount,0)+imported.sales;const expenses=store.entries.filter(x=>x.type==="expense").reduce((s,x)=>s+x.amount,0)+imported.expenses;const assets=store.entries.filter(x=>x.type==="asset").reduce((s,x)=>s+x.amount,0);const liabilities=store.entries.filter(x=>x.type==="liability").reduce((s,x)=>s+x.amount,0)+imported.invoices;return {income,expenses,assets,liabilities,profit:income-expenses,gst:store.profile.gstRegistered?(income-expenses)/11:0}},[store.entries,store.profile.gstRegistered,imported]);
 const addEntry=(e:FormEvent)=>{e.preventDefault();if(!entry.description.trim()||entry.amount<=0)return;setStore(s=>({...s,entries:[{id:id("entry"),...entry,date:entry.date||new Date().toISOString().slice(0,10),source:"Manual"},...s.entries]}));setEntry({date:"",type:"income",account:"Sales",description:"",amount:0})};
 const addPayment=(e:FormEvent)=>{e.preventDefault();if(!payment.customer.trim()||payment.amount<=0)return;setStore(s=>({...s,payments:[{id:id("payment"),...payment,date:payment.date||new Date().toISOString().slice(0,10)},...s.payments]}));setPayment({customer:"",reference:"",amount:0,method:"Bank transfer",date:""})};
 const printDocument=(kind:"Quote"|"Invoice"|"Receipt")=>{const name=prompt(`${kind} customer name`)||"Customer";const description=prompt(`${kind} description`)||"Business services";const amount=Number(prompt(`${kind} total amount`)||0);const w=window.open("","_blank","width=850,height=900");if(!w)return;const gst=store.profile.gstRegistered?amount/11:0;w.document.write(`<html><head><title>${kind}</title><style>body{font-family:Arial;padding:48px;color:#132a3a}header{display:flex;justify-content:space-between;border-bottom:3px solid #0c5577;padding-bottom:20px}table{width:100%;border-collapse:collapse;margin-top:35px}th,td{padding:14px;border-bottom:1px solid #ccd8de;text-align:left}.total{text-align:right;font-size:24px;margin-top:30px}</style></head><body><header><div><h1>${store.profile.name||"Business Lifeline Business"}</h1><p>ABN ${store.profile.abn||"Not supplied"}<br>${store.profile.address}<br>${store.profile.email} ${store.profile.phone}</p></div><div><h2>${kind.toUpperCase()}</h2><p>Date ${new Date().toLocaleDateString("en-AU")}<br>Terms ${store.profile.paymentTerms} days</p></div></header><h3>To: ${name}</h3><table><tr><th>Description</th><th>Amount</th></tr><tr><td>${description}</td><td>${money(amount)}</td></tr></table>${store.profile.gstRegistered?`<p>GST included: ${money(gst)}</p>`:""}<p class="total"><strong>Total ${money(amount)}</strong></p><script>window.print()</script></body></html>`);w.document.close()};
 return <section className="native-finance">
  <header><div><small>WILBUR WONKA NATIVE BUSINESS ENGINE</small><h2>Finance, documents and provider control</h2><p>Own the ledger, reporting, documents and provider connections while keeping external services replaceable.</p></div></header>
  <nav>{([['overview','Overview'],['ledger','Native Ledger'],['documents','Quotes & Invoices'],['payments','Payments'],['providers','Provider Layer']] as const).map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</nav>
  {tab==="overview"&&<main><div className="nf-kpis"><article><small>Income</small><strong>{money(totals.income)}</strong></article><article><small>Expenses</small><strong>{money(totals.expenses)}</strong></article><article><small>Operating result</small><strong>{money(totals.profit)}</strong></article><article><small>Liabilities</small><strong>{money(totals.liabilities)}</strong></article></div><div className="nf-grid"><section><h3>Business identity</h3><label>Business name<input value={store.profile.name} onChange={e=>setStore(s=>({...s,profile:{...s.profile,name:e.target.value}}))}/></label><label>ABN<input value={store.profile.abn} onChange={e=>setStore(s=>({...s,profile:{...s.profile,abn:e.target.value}}))}/></label><label>Email<input value={store.profile.email} onChange={e=>setStore(s=>({...s,profile:{...s.profile,email:e.target.value}}))}/></label><label>Phone<input value={store.profile.phone} onChange={e=>setStore(s=>({...s,profile:{...s.profile,phone:e.target.value}}))}/></label><label>Address<textarea value={store.profile.address} onChange={e=>setStore(s=>({...s,profile:{...s.profile,address:e.target.value}}))}/></label><label className="check"><input type="checkbox" checked={store.profile.gstRegistered} onChange={e=>setStore(s=>({...s,profile:{...s.profile,gstRegistered:e.target.checked}}))}/> GST registered</label></section><section><h3>Live finance position</h3><p>Imported operating sales: <strong>{money(imported.sales)}</strong></p><p>Imported operating expenses: <strong>{money(imported.expenses)}</strong></p><p>Outstanding operating invoices: <strong>{money(imported.invoices)}</strong></p><p>Estimated GST position: <strong>{money(totals.gst)}</strong></p><p>Assets recorded: <strong>{money(totals.assets)}</strong></p><p className="note">This is an internal operating ledger and must be professionally reviewed before tax lodgement.</p></section></div></main>}
  {tab==="ledger"&&<main><div className="nf-grid"><form onSubmit={addEntry}><h3>Add ledger entry</h3><input type="date" value={entry.date} onChange={e=>setEntry({...entry,date:e.target.value})}/><select value={entry.type} onChange={e=>setEntry({...entry,type:e.target.value as Entry['type']})}><option value="income">Income</option><option value="expense">Expense</option><option value="asset">Asset</option><option value="liability">Liability</option></select><input placeholder="Account" value={entry.account} onChange={e=>setEntry({...entry,account:e.target.value})}/><input placeholder="Description" value={entry.description} onChange={e=>setEntry({...entry,description:e.target.value})}/><input type="number" step="0.01" placeholder="Amount" value={entry.amount||''} onChange={e=>setEntry({...entry,amount:+e.target.value})}/><button>Add entry</button></form><section><h3>Chart summary</h3>{(['income','expense','asset','liability'] as const).map(t=><p key={t}><strong>{t}</strong> {money(store.entries.filter(x=>x.type===t).reduce((s,x)=>s+x.amount,0))}</p>)}</section></div><div className="nf-table">{store.entries.map(x=><article key={x.id}><span>{x.date}</span><strong>{x.account}</strong><span>{x.description}</span><b>{money(x.amount)}</b><small>{x.type} · {x.source}</small></article>)}</div></main>}
  {tab==="documents"&&<main><div className="nf-actions"><button onClick={()=>printDocument('Quote')}>Create printable quote</button><button onClick={()=>printDocument('Invoice')}>Create printable invoice</button><button onClick={()=>printDocument('Receipt')}>Create printable receipt</button></div><section><h3>Document engine</h3><p>Documents use your saved business identity, ABN, GST status and payment terms. The current version generates a clean printable/PDF-ready document in the browser.</p><p className="note">Automated email delivery, numbering, line items, deposits, recurring invoices and customer acceptance are the next native document stage.</p></section></main>}
  {tab==="payments"&&<main><div className="nf-grid"><form onSubmit={addPayment}><h3>Record payment</h3><input placeholder="Customer" value={payment.customer} onChange={e=>setPayment({...payment,customer:e.target.value})}/><input placeholder="Invoice/reference" value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/><input type="number" step="0.01" placeholder="Amount" value={payment.amount||''} onChange={e=>setPayment({...payment,amount:+e.target.value})}/><select value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})}><option>Bank transfer</option><option>Cash</option><option>Card</option><option>Other</option></select><input type="date" value={payment.date} onChange={e=>setPayment({...payment,date:e.target.value})}/><button>Record payment</button></form><section><h3>Payments received</h3><strong>{money(store.payments.reduce((s,x)=>s+x.amount,0))}</strong>{store.payments.map(x=><p key={x.id}>{x.customer} · {x.reference} · {money(x.amount)} · {x.method}</p>)}</section></div></main>}
  {tab==="providers"&&<main><div className="provider-list">{store.providers.map(p=><article key={p.id}><div><small>{p.category}</small><h3>{p.label}</h3><p>{p.provider}</p></div><select value={p.mode} onChange={e=>setStore(s=>({...s,providers:s.providers.map(x=>x.id===p.id?{...x,mode:e.target.value as Provider['mode']}:x)}))}><option value="internal">Business Lifeline internal</option><option value="external">External provider active</option><option value="planned">Adapter planned</option></select></article>)}</div><p className="note">No secret API keys are stored here. Production integrations must use secure server-side credentials and provider-specific approval.</p></main>}
 </section>
}