"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type HubView = "automation" | "crm" | "quotes" | "suppliers" | "expenses" | "roster";
type Stage = "new" | "contacted" | "quoted" | "won" | "lost";
type Customer = { id: string; name: string; contact: string; stage: Stage; value: number; nextAction: string; due: string };
type Quote = { id: string; customer: string; description: string; amount: number; status: "draft" | "sent" | "accepted" | "invoiced" | "paid"; createdAt: string };
type SupplierOrder = { id: string; supplier: string; items: string; amount: number; status: "draft" | "ordered" | "received" | "paid"; due: string };
type Expense = { id: string; supplier: string; category: string; amount: number; paidBy: string; date: string; receipt: string };
type Shift = { id: string; person: string; role: string; date: string; start: string; end: string; status: "planned" | "confirmed" | "completed" };
type AutomationEvent = { id: string; title: string; detail: string; createdAt: string };
type HubStore = { customers: Customer[]; quotes: Quote[]; orders: SupplierOrder[]; expenses: Expense[]; shifts: Shift[]; events: AutomationEvent[] };

const STORAGE_KEY = "business-lifeline-operating-automation-v1";
const blankStore: HubStore = { customers: [], quotes: [], orders: [], expenses: [], shifts: [], events: [] };
const views: Array<{ id: HubView; label: string; detail: string }> = [
  { id: "automation", label: "Automation", detail: "Connected updates across the business" },
  { id: "crm", label: "CRM Pipeline", detail: "Leads, follow-ups and customer value" },
  { id: "quotes", label: "Quotes & Invoices", detail: "Move work from quote to paid" },
  { id: "suppliers", label: "Suppliers & POs", detail: "Purchase orders and receiving" },
  { id: "expenses", label: "Expenses", detail: "Costs, categories and receipts" },
  { id: "roster", label: "Roster", detail: "Shifts, roles and completion" },
];

function readStore(): HubStore {
  if (typeof window === "undefined") return blankStore;
  try {
    const parsed = JSON.parse(window.localStorage.getItem(STORAGE_KEY) ?? "null") as Partial<HubStore> | null;
    return parsed ? { ...blankStore, ...parsed } as HubStore : blankStore;
  } catch { return blankStore; }
}

const event = (title: string, detail: string): AutomationEvent => ({ id: `event-${Date.now()}-${Math.random()}`, title, detail, createdAt: new Date().toISOString() });

export function OperatingAutomationHub() {
  const [active, setActive] = useState<HubView>("automation");
  const [store, setStore] = useState<HubStore>(blankStore);
  const [ready, setReady] = useState(false);
  const [customer, setCustomer] = useState({ name: "", contact: "", value: 0, nextAction: "", due: "" });
  const [quote, setQuote] = useState({ customer: "", description: "", amount: 0 });
  const [order, setOrder] = useState({ supplier: "", items: "", amount: 0, due: "" });
  const [expense, setExpense] = useState({ supplier: "", category: "Stock", amount: 0, paidBy: "Card", date: "", receipt: "" });
  const [shift, setShift] = useState({ person: "", role: "", date: "", start: "", end: "" });

  useEffect(() => { setStore(readStore()); setReady(true); }, []);
  useEffect(() => { if (ready) window.localStorage.setItem(STORAGE_KEY, JSON.stringify(store)); }, [store, ready]);

  const pipelineValue = useMemo(() => store.customers.filter((item) => !["lost", "won"].includes(item.stage)).reduce((sum, item) => sum + item.value, 0), [store.customers]);
  const outstanding = useMemo(() => store.quotes.filter((item) => !["paid"].includes(item.status)).reduce((sum, item) => sum + item.amount, 0), [store.quotes]);
  const expensesTotal = useMemo(() => store.expenses.reduce((sum, item) => sum + item.amount, 0), [store.expenses]);

  const addCustomer = (e: FormEvent) => { e.preventDefault(); if (!customer.name.trim()) return; const item: Customer = { id: `customer-${Date.now()}`, ...customer, name: customer.name.trim(), stage: "new" }; setStore((s) => ({ ...s, customers: [item, ...s.customers], events: [event("New CRM lead", `${item.name} added with potential value ${item.value.toLocaleString("en-AU", { style: "currency", currency: "AUD" })}.`), ...s.events] })); setCustomer({ name: "", contact: "", value: 0, nextAction: "", due: "" }); };
  const advanceCustomer = (id: string) => setStore((s) => { const order: Stage[] = ["new", "contacted", "quoted", "won"]; const current = s.customers.find((item) => item.id === id); if (!current) return s; const next = order[Math.min(order.indexOf(current.stage) + 1, order.length - 1)]; const updated = s.customers.map((item) => item.id === id ? { ...item, stage: next } : item); const events = next === "won" ? [event("Customer won", `${current.name} moved to won. Create the job and invoice next.`), ...s.events] : s.events; return { ...s, customers: updated, events }; });
  const addQuote = (e: FormEvent) => { e.preventDefault(); if (!quote.customer.trim()) return; const item: Quote = { id: `quote-${Date.now()}`, ...quote, customer: quote.customer.trim(), status: "draft", createdAt: new Date().toISOString() }; setStore((s) => ({ ...s, quotes: [item, ...s.quotes], events: [event("Quote created", `${item.customer}: ${item.amount.toLocaleString("en-AU", { style: "currency", currency: "AUD" })}.`), ...s.events] })); setQuote({ customer: "", description: "", amount: 0 }); };
  const advanceQuote = (id: string) => setStore((s) => { const order: Quote["status"][] = ["draft", "sent", "accepted", "invoiced", "paid"]; const current = s.quotes.find((item) => item.id === id); if (!current) return s; const next = order[Math.min(order.indexOf(current.status) + 1, order.length - 1)]; return { ...s, quotes: s.quotes.map((item) => item.id === id ? { ...item, status: next } : item), events: [event(`Quote ${next}`, `${current.customer} · ${current.amount.toLocaleString("en-AU", { style: "currency", currency: "AUD" })}.`), ...s.events] }; });
  const addOrder = (e: FormEvent) => { e.preventDefault(); if (!order.supplier.trim()) return; const item: SupplierOrder = { id: `po-${Date.now()}`, ...order, supplier: order.supplier.trim(), status: "draft" }; setStore((s) => ({ ...s, orders: [item, ...s.orders], events: [event("Purchase order drafted", `${item.supplier}: ${item.items}.`), ...s.events] })); setOrder({ supplier: "", items: "", amount: 0, due: "" }); };
  const advanceOrder = (id: string) => setStore((s) => { const stages: SupplierOrder["status"][] = ["draft", "ordered", "received", "paid"]; const current = s.orders.find((item) => item.id === id); if (!current) return s; const next = stages[Math.min(stages.indexOf(current.status) + 1, stages.length - 1)]; return { ...s, orders: s.orders.map((item) => item.id === id ? { ...item, status: next } : item), events: [event(`Purchase order ${next}`, `${current.supplier}: ${current.items}.`), ...s.events] }; });
  const addExpense = (e: FormEvent) => { e.preventDefault(); if (!expense.supplier.trim() || expense.amount <= 0) return; const item: Expense = { id: `expense-${Date.now()}`, ...expense, supplier: expense.supplier.trim() }; setStore((s) => ({ ...s, expenses: [item, ...s.expenses], events: [event("Expense recorded", `${item.supplier} · ${item.category} · ${item.amount.toLocaleString("en-AU", { style: "currency", currency: "AUD" })}.`), ...s.events] })); setExpense({ supplier: "", category: "Stock", amount: 0, paidBy: "Card", date: "", receipt: "" }); };
  const addShift = (e: FormEvent) => { e.preventDefault(); if (!shift.person.trim()) return; const item: Shift = { id: `shift-${Date.now()}`, ...shift, person: shift.person.trim(), status: "planned" }; setStore((s) => ({ ...s, shifts: [item, ...s.shifts], events: [event("Shift planned", `${item.person} · ${item.date} ${item.start}-${item.end}.`), ...s.events] })); setShift({ person: "", role: "", date: "", start: "", end: "" }); };

  return <section className="automation-hub">
    <div className="automation-hero"><div><p className="eyebrow">CONNECTED OPERATING ENGINE</p><h2>Enter it once. Update the whole business.</h2><p>This foundation connects customer activity, quotes, supplier orders, expenses and staff shifts through one automation feed.</p></div><div className="automation-metrics"><span><strong>{pipelineValue.toLocaleString("en-AU", { style: "currency", currency: "AUD", maximumFractionDigits: 0 })}</strong><small>Open pipeline</small></span><span><strong>{outstanding.toLocaleString("en-AU", { style: "currency", currency: "AUD", maximumFractionDigits: 0 })}</strong><small>Quotes/invoices</small></span><span><strong>{expensesTotal.toLocaleString("en-AU", { style: "currency", currency: "AUD", maximumFractionDigits: 0 })}</strong><small>Expenses</small></span></div></div>
    <nav className="automation-nav">{views.map((view) => <button type="button" key={view.id} className={active === view.id ? "active" : ""} onClick={() => setActive(view.id)}><strong>{view.label}</strong><small>{view.detail}</small></button>)}</nav>
    {active === "automation" && <div className="automation-feed"><div><p className="eyebrow">AUTOMATION FEED</p><h3>What updated across the system</h3></div>{store.events.slice(0, 20).map((item) => <article key={item.id}><strong>{item.title}</strong><p>{item.detail}</p><small>{new Date(item.createdAt).toLocaleString()}</small></article>)}{store.events.length === 0 && <p>No connected activity yet. Add a customer, quote, order, expense or shift.</p>}</div>}
    {active === "crm" && <Module title="CRM pipeline" count={store.customers.length} form={<form onSubmit={addCustomer}><label>Customer or lead<input value={customer.name} onChange={(e) => setCustomer({ ...customer, name: e.target.value })} required /></label><label>Contact details<input value={customer.contact} onChange={(e) => setCustomer({ ...customer, contact: e.target.value })} /></label><label>Potential value<input type="number" min="0" value={customer.value} onChange={(e) => setCustomer({ ...customer, value: Number(e.target.value) })} /></label><label>Next action<input value={customer.nextAction} onChange={(e) => setCustomer({ ...customer, nextAction: e.target.value })} /></label><label>Due<input type="date" value={customer.due} onChange={(e) => setCustomer({ ...customer, due: e.target.value })} /></label><button className="button primary">Add lead</button></form>}>{store.customers.map((item) => <Record key={item.id} title={item.name} detail={`${item.contact || "No contact"} · ${item.nextAction || "No next action"}`} meta={`${item.stage} · ${item.value.toLocaleString("en-AU", { style: "currency", currency: "AUD" })}`} action={() => advanceCustomer(item.id)} actionLabel="Advance stage" />)}</Module>}
    {active === "quotes" && <Module title="Quotes and invoices" count={store.quotes.length} form={<form onSubmit={addQuote}><label>Customer<input value={quote.customer} onChange={(e) => setQuote({ ...quote, customer: e.target.value })} required /></label><label>Description<textarea value={quote.description} onChange={(e) => setQuote({ ...quote, description: e.target.value })} /></label><label>Amount<input type="number" min="0" step="0.01" value={quote.amount} onChange={(e) => setQuote({ ...quote, amount: Number(e.target.value) })} /></label><button className="button primary">Create quote</button></form>}>{store.quotes.map((item) => <Record key={item.id} title={item.customer} detail={item.description} meta={`${item.status} · ${item.amount.toLocaleString("en-AU", { style: "currency", currency: "AUD" })}`} action={() => advanceQuote(item.id)} actionLabel="Advance" />)}</Module>}
    {active === "suppliers" && <Module title="Suppliers and purchase orders" count={store.orders.length} form={<form onSubmit={addOrder}><label>Supplier<input value={order.supplier} onChange={(e) => setOrder({ ...order, supplier: e.target.value })} required /></label><label>Items<textarea value={order.items} onChange={(e) => setOrder({ ...order, items: e.target.value })} /></label><label>Amount<input type="number" min="0" step="0.01" value={order.amount} onChange={(e) => setOrder({ ...order, amount: Number(e.target.value) })} /></label><label>Due<input type="date" value={order.due} onChange={(e) => setOrder({ ...order, due: e.target.value })} /></label><button className="button primary">Create purchase order</button></form>}>{store.orders.map((item) => <Record key={item.id} title={item.supplier} detail={item.items} meta={`${item.status} · ${item.amount.toLocaleString("en-AU", { style: "currency", currency: "AUD" })}`} action={() => advanceOrder(item.id)} actionLabel="Advance" />)}</Module>}
    {active === "expenses" && <Module title="Expense capture" count={store.expenses.length} form={<form onSubmit={addExpense}><label>Supplier<input value={expense.supplier} onChange={(e) => setExpense({ ...expense, supplier: e.target.value })} required /></label><label>Category<select value={expense.category} onChange={(e) => setExpense({ ...expense, category: e.target.value })}><option>Stock</option><option>Operating</option><option>Vehicle</option><option>Marketing</option><option>Wages</option><option>Other</option></select></label><label>Amount<input type="number" min="0" step="0.01" value={expense.amount} onChange={(e) => setExpense({ ...expense, amount: Number(e.target.value) })} /></label><label>Paid by<input value={expense.paidBy} onChange={(e) => setExpense({ ...expense, paidBy: e.target.value })} /></label><label>Date<input type="date" value={expense.date} onChange={(e) => setExpense({ ...expense, date: e.target.value })} /></label><label>Receipt reference<input value={expense.receipt} onChange={(e) => setExpense({ ...expense, receipt: e.target.value })} /></label><button className="button primary">Record expense</button></form>}>{store.expenses.map((item) => <Record key={item.id} title={item.supplier} detail={`${item.category} · ${item.paidBy}`} meta={item.amount.toLocaleString("en-AU", { style: "currency", currency: "AUD" })} />)}</Module>}
    {active === "roster" && <Module title="Roster and shifts" count={store.shifts.length} form={<form onSubmit={addShift}><label>Person<input value={shift.person} onChange={(e) => setShift({ ...shift, person: e.target.value })} required /></label><label>Role<input value={shift.role} onChange={(e) => setShift({ ...shift, role: e.target.value })} /></label><label>Date<input type="date" value={shift.date} onChange={(e) => setShift({ ...shift, date: e.target.value })} /></label><label>Start<input type="time" value={shift.start} onChange={(e) => setShift({ ...shift, start: e.target.value })} /></label><label>End<input type="time" value={shift.end} onChange={(e) => setShift({ ...shift, end: e.target.value })} /></label><button className="button primary">Add shift</button></form>}>{store.shifts.map((item) => <Record key={item.id} title={item.person} detail={item.role} meta={`${item.date} · ${item.start}-${item.end} · ${item.status}`} />)}</Module>}
  </section>;
}

function Module({ title, count, form, children }: { title: string; count: number; form: React.ReactNode; children: React.ReactNode }) { return <div className="automation-module"><section className="automation-register"><div className="section-heading"><div><p className="eyebrow">OPERATING REGISTER</p><h3>{title}</h3></div><span>{count} records</span></div>{children}{count === 0 && <p>No records yet.</p>}</section><aside className="automation-form">{form}</aside></div>; }
function Record({ title, detail, meta, action, actionLabel }: { title: string; detail: string; meta: string; action?: () => void; actionLabel?: string }) { return <article className="automation-record"><div><strong>{title}</strong><p>{detail}</p><small>{meta}</small></div>{action && <button type="button" onClick={action}>{actionLabel}</button>}</article>; }
