"use client";
import{useEffect,useMemo,useState}from"react";
type Item={id:string;type:string;title:string;subtitle:string};
const sources=[["business-lifeline-crm-v1",["accounts","contacts","opportunities","activities"]],["business-lifeline-operations-v1",["projects","projectTasks","purchaseOrders","inventory","serviceOrders","productionOrders"]],["business-lifeline-operating-platform-v1",["customers","products","sales","quotes"]]] as const;
const label=(x:any)=>String(x?.name||x?.title||x?.description||x?.customerName||x?.productId||x?.id||"Record");
export function SharedPlatformShell(){
 const[open,setOpen]=useState(false),[q,setQ]=useState(""),[items,setItems]=useState<Item[]>([]),[notice,setNotice]=useState<string[]>([]);
 const refresh=()=>{const out:Item[]=[];for(const[k,groups]of sources){try{const s=JSON.parse(localStorage.getItem(k)||"{}");for(const g of groups)for(const x of Array.isArray(s[g])?s[g]:[])out.push({id:String(x.id||x.productId||crypto.randomUUID()),type:g,title:label(x),subtitle:String(x.email||x.status||x.stageId||x.locationId||"")})}catch{}}setItems(out);const n:string[]=[];try{const o=JSON.parse(localStorage.getItem("business-lifeline-operations-v1")||"{}");const low=(o.inventory||[]).filter((x:any)=>Number(x.available)<=Number(x.reorderPoint||0));if(low.length)n.push(low.length+" stock item"+(low.length===1?"":"s")+" at reorder point");const blocked=(o.projects||[]).filter((x:any)=>x.status==="blocked");if(blocked.length)n.push(blocked.length+" blocked job"+(blocked.length===1?"":"s"));}catch{}setNotice(n)};
 useEffect(()=>{refresh();const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setOpen(v=>!v)}if(e.key==="Escape")setOpen(false)};window.addEventListener("keydown",key);window.addEventListener("business-lifeline-operating-updated",refresh);return()=>{window.removeEventListener("keydown",key);window.removeEventListener("business-lifeline-operating-updated",refresh)}},[]);
 const found=useMemo(()=>{const s=q.trim().toLowerCase();return(s?items.filter(x=>(x.title+" "+x.subtitle+" "+x.type).toLowerCase().includes(s)):items).slice(0,30)},[items,q]);
 return <><div className="shared-platform-bar" role="navigation" aria-label="Shared platform controls"><button onClick={()=>setOpen(true)} aria-keyshortcuts="Control+K Meta+K">Search everything <kbd>⌘/Ctrl K</kbd></button><span aria-live="polite">{notice.length?notice.join(" · "):"No operating alerts"}</span></div>{open&&<div className="shared-platform-backdrop" role="dialog" aria-modal="true" aria-label="Global search"><section className="shared-platform-search"><header><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search customers, jobs, products, quotes…" aria-label="Search all business records"/><button onClick={()=>setOpen(false)} aria-label="Close search">×</button></header>{found.length?<div className="shared-results">{found.map(x=><article key={x.type+":"+x.id} tabIndex={0}><small>{x.type.replaceAll("-"," ")}</small><strong>{x.title}</strong><span>{x.subtitle||"Business record"}</span></article>)}</div>:<div className="shared-empty"><strong>No records found</strong><span>Try a customer, job, product, quote or status.</span></div>}</section></div>}</>
}