"use client";
import{useEffect,useMemo,useState}from"react";
import{can,evaluateAutomation,type AutomationRule,type AuditEvent,type PlatformRole}from"@/lib/shared-platform";
type Item={id:string;type:string;title:string;subtitle:string};
const sources=[["business-lifeline-crm-v1",["accounts","contacts","opportunities","activities"]],["business-lifeline-operations-v1",["projects","projectTasks","purchaseOrders","inventory","serviceOrders","productionOrders"]],["business-lifeline-operating-platform-v1",["customers","products","sales","quotes"]]] as const;
const label=(x:any)=>String(x?.name||x?.title||x?.description||x?.customerName||x?.productId||x?.id||"Record");
export function SharedPlatformShell(){
 const[open,setOpen]=useState(false),[q,setQ]=useState(""),[items,setItems]=useState<Item[]>([]),[notice,setNotice]=useState<string[]>([]),[panel,setPanel]=useState<"search"|"command">("search"),[role,setRole]=useState<PlatformRole>("owner"),[rules,setRules]=useState<AutomationRule[]>([]),[audit,setAudit]=useState<AuditEvent[]>([]);
 const refresh=()=>{const out:Item[]=[];for(const[k,groups]of sources){try{const s=JSON.parse(localStorage.getItem(k)||"{}");for(const g of groups)for(const x of Array.isArray(s[g])?s[g]:[])out.push({id:String(x.id||x.productId||crypto.randomUUID()),type:g,title:label(x),subtitle:String(x.email||x.status||x.stageId||x.locationId||"")})}catch{}}setItems(out);const n:string[]=[];try{const o=JSON.parse(localStorage.getItem("business-lifeline-operations-v1")||"{}");const low=(o.inventory||[]).filter((x:any)=>Number(x.available)<=Number(x.reorderPoint||0));if(low.length)n.push(low.length+" stock item"+(low.length===1?"":"s")+" at reorder point");const blocked=(o.projects||[]).filter((x:any)=>x.status==="blocked");if(blocked.length)n.push(blocked.length+" blocked job"+(blocked.length===1?"":"s"));}catch{}setNotice(n)};
 useEffect(()=>{try{setRole((localStorage.getItem("business-lifeline-role-v1")||"owner") as PlatformRole);setRules(JSON.parse(localStorage.getItem("business-lifeline-automation-rules-v1")||"[]"));setAudit(JSON.parse(localStorage.getItem("business-lifeline-audit-v1")||"[]"))}catch{}refresh();const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setOpen(v=>!v)}if(e.key==="Escape")setOpen(false)};window.addEventListener("keydown",key);window.addEventListener("business-lifeline-operating-updated",refresh);return()=>{window.removeEventListener("keydown",key);window.removeEventListener("business-lifeline-operating-updated",refresh)}},[]);
 const found=useMemo(()=>{const s=q.trim().toLowerCase();return(s?items.filter(x=>(x.title+" "+x.subtitle+" "+x.type).toLowerCase().includes(s)):items).slice(0,30)},[items,q]);
 const addRule=()=>{if(!can(role,"automation.manage"))return;const r:AutomationRule={id:"rule-"+Date.now(),name:"Low stock alert",enabled:true,trigger:"stock-low",recordType:"inventory",action:"notify",actionValue:"Reorder stock"};const next=[r,...rules];setRules(next);localStorage.setItem("business-lifeline-automation-rules-v1",JSON.stringify(next))};
 return <><div className="shared-platform-bar" role="navigation" aria-label="Shared platform controls"><button onClick={()=>{setPanel("search");setOpen(true)}} aria-keyshortcuts="Control+K Meta+K">Search everything <kbd>⌘/Ctrl K</kbd></button><button onClick={()=>{setPanel("command");setOpen(true)}}>Command centre</button><span aria-live="polite">{notice.length?notice.join(" · "):"No operating alerts"}</span></div>{open&&<div className="shared-platform-backdrop" role="dialog" aria-modal="true" aria-label="Global search"><section className="shared-platform-search"><header>{panel==="search"?<input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search customers, jobs, products, quotes…" aria-label="Search all business records"/>:<strong>Business command centre</strong>}<button onClick={()=>setOpen(false)} aria-label="Close search">×</button></header>{panel==="command"?<div className="shared-command"><div className="shared-kpis"><article><small>Records</small><strong>{items.length}</strong></article><article><small>Alerts</small><strong>{notice.length}</strong></article><article><small>Automations</small><strong>{rules.filter(r=>r.enabled).length}</strong></article><article><small>Role</small><strong>{role}</strong></article></div><section><h3>Automation builder</h3>{can(role,"automation.manage")?<button onClick={addRule}>+ Low-stock notification rule</button>:<p>Your role cannot manage automations.</p>}{rules.map(r=><p key={r.id}><strong>{r.name}</strong> · {r.trigger} → {r.action}</p>)}</section><section><h3>Audit history</h3>{can(role,"audit.read")?(audit.length?audit.slice(0,10).map(a=><p key={a.id}>{a.at} · {a.summary}</p>):<p>No audit events yet.</p>):<p>Your role cannot view audit history.</p>}</section></div>:found.length?<div className="shared-results">{found.map(x=><article key={x.type+":"+x.id} tabIndex={0}><small>{x.type.replaceAll("-"," ")}</small><strong>{x.title}</strong><span>{x.subtitle||"Business record"}</span></article>)}</div>:<div className="shared-empty"><strong>No records found</strong><span>Try a customer, job, product, quote or status.</span></div>}</section></div>}</>
}